### DISCUSSION TITLE
Trouble with Nested TOCs in DocFX for Generated Content

### DISCUSSION THREAD

**Discussion by dadaPipes** [dotnet/docfx#10584] [Q&A]
I am encountering an issue with nested TOCs in DocFX for generated content.
assert/ is where the generated content is.

Works with no problems:

```
- name: Docs
  href: docs/
- name: v3
  href: v3-1.0.0/assert/

```  

This does not work:

```
- name: Docs
  href: docs/
- name: v3
  href: v3/
  items:
    - name: v3-1.0.0 
      href: v3-1.0.0/assert/
```

When I --serve, then I get the following warning:
**../Docs\toc.yml: warning: Unable to find either toc.yml or toc.md inside v3/. Make sure the file is included in config file docfx.json!**

When I navigate to the content it looks like this: 

![Screenshot 2025-03-10 235636](https://github.com/user-attachments/assets/d9513060-bd28-4c17-a5d0-f42fbea64f08)
