### DISCUSSION TITLE
Schema: set a field as markdown

### DISCUSSION THREAD

**Discussion by antongit** [dotnet/docfx#8134] [Q&A]
Hello,

unfortunately I'm stuck telling docfx that one of my fields in .yml doc should be markdown-parsed.

My yaml looks like:

```
### YamlMime:ContributionComments
---
uid: "MYUID"
comments: 
   - comment: 
        nid: "NID"
        user: "USER"
        created: "DATE"
        body: |-
          BODY WITH MARKDOWN
...
```

My schema is:

```
{
    "$schema": "https://dotnet.github.io/docfx/schemas/v1.0/schema.json#",
    "version": "1.0.0",
    "id": "contribution-comments",
    "description": "The Schema for Contributions-Comments",
    "title": "ContributionComments",
    "type": "object",
    "properties": {
        "uid": {
            "type": "string",
            "contentType": "uid"
        },
        "comments": {
            "type": "array",
            "items": {
                "comment": {
                    "type": "object",
                    "properties": {
                        "nid": {
                            "type": "string"
                        },
                        "user": {
                            "type": "string"
                        },
                        "created": {
                            "type": "string"
                        },
                        "body": {
                            "type": "string",
                            "contentType": "markdown"
                        }
                    }
                }
            }
        }
    },
    "xrefProperties": [ "comments" ]
}
```

Somehow the `body` is rendered as is without going through the Markdown parser.
Maybe someone can spot the problem?

Thank you!

Best,
Anton
