### DISCUSSION TITLE
Unable to set landing page

### DISCUSSION THREAD

**Discussion by ghost** [dotnet/docfx#8261] [General]
**Operating System**: Windows

**DocFX Version Used**: 2.59.4

**Template used**: ? 
```
    "template": [
      "default",
      "_templates/last-modified"
    ],
```

**Steps to Reproduce**:

1) Use the following root toc (resource: DocFX [page](https://dotnet.github.io/docfx/tutorial/intro_toc.html)) to set a markdown doc in a nested folder as the home page for localhost:8080. My understanding is that the root toc.yml generates the top nav bar, and nested toc.ymls generate the vertical left bar. Combining them doesn't seem like a good idea.

```
- name: Troubleshooting Guides
  href: tsgs/toc.yml
  topicHref: tsgs/aadlcm-oncall-handbook/lcm-dependency-map.md
```

2) Here's the nested /tsgs/toc.yml:

```
- name: AADLCM OnCall handbook
  items:
  - name: AAD LCW OnCall HandBook
    href: aadlcm-oncall-handbook/aad-lcw-oncall-handbook.md
  - name: LCM Dependency Map
    href: aadlcm-oncall-handbook/lcm-dependency-map.md
```

3) Run DocFX locally on the docfx.json in the root folder.

**Expected Behavior**:

Should see the Markdown article specified by the topicHref as the landing page.

**Actual Behavior**:

I get an index listing:
![image](https://user-images.githubusercontent.com/86677757/198735351-b9c18b04-efdd-4d92-b017-4d6a69dc8a91.png)
