### DISCUSSION TITLE
Question: --serve can only render out "type: method", cannot render out "type: attributes"

### DISCUSSION THREAD

**Discussion by Wuliyuanulb** [dotnet/docfx#8268] [General]
The generated api in yaml file is like this:
```
- class: ***
  fullName: ***
  langs:
  - python
  module: ***
  name: ***
  source:
    id: ***
    path: ***
    remote:
      branch: ***
      path: ***
      repo: ***
    startLine: ***
  summary: ***
  syntax:
    return:
      description: ***
      type:
      - str
  type: attribute
  uid: ***
```
Where the type of this API is **attribute**.
After I use docfx.exe docfx.json --serve
the local website can only show API where type is "**Method**".

And I followed this: https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#2-attribute-filter-rules, manually make my json file like this: (cause docfx.exe metadata --filter <path relative to baseDir or absolutepath> didn't work for me)
```
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/**.csproj"
          ]
        }
      ],
      "dest": "api",
      "filter": "filterConfig.yml"
    }
  ],
```
where filterConfig.yml is:
```
apiRules:
- include:
    type: attribute
attributeRules:
- include:
    type: attribute
```
But it still cannot work.

So, could you kindly help me solve this? Thanks a lot. 
You can directly reach me on Teams, I am liyw.

Thanks
