### DISCUSSION TITLE
Categorize Properties and Methods in the TOC for .NET Documentation

### DISCUSSION THREAD

**Discussion by UmaHarano** [dotnet/docfx#9891] [General]
Hi,

On Microsoft's site for .NET classes, I see the Properties and Methods are categorized using separate TOC folders. In the screenshot below, notice how `List<T>` class has Constructors, Properties and Methods as subfolders.  Like this:

![image](https://github.com/dotnet/docfx/assets/6740984/348b651c-0d55-4ef4-844c-fd5822e386b5)

I am using DocFX to create documentation for my .NET assemblies. I get all the members of a class listed directly under the class. Is there a docfx setting I can use to generate a TOC that separates the methods and properties into folders like the screenshot above?

Thanks!
Uma

**Comment by filzrev** [comment]
>  Is there a docfx setting I can use to generate a TOC that separates the methods and properties into folders like the screenshot above?

Try to use `"memberLayout": "separatePages"` option.
https://dotnet.github.io/docfx/reference/docfx-json-reference.html?#memberlayout

**Reply by UmaHarano** [reply]
Hi!
I am using the memberLayout option. This option allows me to create a separate html page for every member (property and types). So that works nicely.
But in the "master" TOC - I want to group properties and methods separately. Currently, I get all the members of a class in one list under the namespace.

![image](https://github.com/dotnet/docfx/assets/6740984/1e13464c-512c-4d6e-9469-4498d1711970)

For reference, on Microsoft's page for `List<T>`, notice the Constructors, Properties and Methods sub folders. I want to get that for my documentation for .NET.

**Reply by filzrev** [reply]
As far as tested on my environment.

TOC items are categorized based on member types (e,g, `Constructors`/`Properties`/`Methods`).
When using `"memberLayout": "separatePages"` option.

Is it able to provide `docfx.json` settings that used to build API document?

---

I've found similar wrong TOC generation behaviors when following conditions met (#9893).

1. Using `"outputType": "mref"` option (default setting)
2. Manually placing TOC file to intermediate directory (e.g. `api/toc.yml`) 
3. Referencing generated TOC with [Nested TOC](https://dotnet.github.io/docfx/docs/table-of-contents.html#nested-tocs) syntax (e.g. `"href" : "net8/toc.yml"`).

**Comment by UmaHarano** [comment]
@filzrev 
This is exactly the issue. Thank you! Any ideas when this will get fixed?

**Comment by filzrev** [comment]
> Any ideas when this will get fixed?

`separatePages` metadata is handled by JavaScript code when using `outputFormat: mref`.
And it seems difficult to fix this issue by changing code to handle `samePage`/`separatePages` options are mixed inside single TOC. 

---

For temporary workaround.
Try to set `memberLayout: SeparatePages` metadata to `Manually created TOC file`.

**Example TOC file**
```
items:
  - name:  API for .NET8
    href: net8/toc.yml
memberLayout: SeparatePages
```

**Comment by UmaHarano** [comment]
Thanks @filzrev 
I tried the workaround and it did not fix the issue for me. This is the yml file I created. Note: I had to put the `-` in front of the memberLayout. I got a build error if I did not add that.

```yml
### YamlMime:TableOfContent
- name: Introduction
  href: introduction.md
- name: Getting Started
  href: getting-started.md
- name: ArcGIS.CoreHost Assembly
  items:
  - name: Namespaces
    href: ../api/toc.yml
- memberLayout: SeparatePages
```

I would love any other suggestions. I am trying to create a .NET API guide using DocFX similar to [this one](https://pro.arcgis.com/en/pro-app/latest/sdk/api-reference/topic1.html#) (which was created using another product).

**Comment by filzrev** [comment]
Is it failed when setting `items:` to root element?

**Example**
```
### YamlMime:TableOfContent
items:
  - name: Introduction
    href: introduction.md
  - name: Getting Started
    href: getting-started.md
  - name: ArcGIS.CoreHost Assembly
    items:
    - name: Namespaces
      href: ../api/toc.yml
memberLayout: SeparatePages
```

`memberLayout` is YAML ExtensibleMember property.
So it need to be set on same hierarchy to root element.
