### ISSUE TITLE
[Bug] DocFx generates incorrect links in "View Source" when building from a tag in Azure DevOps git repo

### ISSUE THREAD

**Issue by Maarty** [dotnet/docfx#10161]
**Describe the bug**
Our builds are usually from a git tag in Azure DevOps, and in this case, the "View Source" button in DocFx is not working.

The link would work if we built from a branch, but not from a tag.

Example of generated link:
https://dev.azure.com/organizationName/projectname/_git/RepoName?path=Src/path/subpath/file.cs&version=GB7.104.0&line=8

7.104.0 is the name of our git tag.

Correct link would end with `GT7.104.0` not `GB7.104.0` as `GB` works only for branches, not tags.

**To Reproduce**
1. Run  CLI dotnet `docfx` on a git tag version of Azure DevOps repo.

**Expected behavior**
The link should end with `GT{tag name}` instead of `GB{tag name}` for builds from a git tag.

**Context:**
- OS: Windows/Linux
- Docfx version: latest

**Comment by VaclavElias** [comment]
This might be similar to my issue. This checkouts from 2 repositories https://github.com/stride3d/stride-docs/blob/staging/.github/workflows/stride-docs-staging-azure.yml

- Stride Docs - From the repository and branch `staging` where the GitHub Action is triggered from
- Stride Engine - Used for the API generation, checkout from another repository, with `master` branch

The documentation manual, tutorials.. honor the settings from the `docfx.json`, so when I click **Edit this page**, it takes you to the correct repo and branch.

```json
"_gitContribute": {
        "repo": "https://github.com/stride3d/stride-docs",
        "branch": "master"
      }
```
But when I want to see the source code for the API, for example here https://stride-doc-staging.azurewebsites.net/latest/en/api/Stride.CompilationMode.html

The View Source links takes you to 

`https://github.com/stride3d/stride/blob/staging/sources/engine/Stride/CompilationMode.cs/#L8` which doesn't exist.

The branch shouldn't be `staging` but `master`.

The GitHub Action (link above) has this:

```
    # Checkout the Stride repository from the default branch
    - name: Checkout Stride (note the LFS)
      uses: actions/checkout@v4
      with:
        repository: stride3d/stride
        token: ${{ secrets.GITHUB_TOKEN }}
        path: stride
        lfs: true
        ref: master
```
It seems like that the current branch `staging` is somehow leaking where it shouldn't 🤣.
