### ISSUE TITLE
[Feature Request] Allow filtering for access modifier

### ISSUE THREAD

**Issue by Falco20019** [dotnet/docfx#10252]
**Is your feature request related to a problem? Please describe.**
I have `includePrivateMembers` enabled since I need `private methods`. But I need to hide `private fields`.

**Describe the solution you'd like**
Allow filtering in a filter config like this:
```yaml
apiRules:
- exclude:
    uidRegex: .*
    accessModifier: private
    type: Field
```

**Describe alternatives you've considered**
Disabling `includePrivateMembers` is not possible since I need the methods. The only alternative I was able to come up with is creating an attribute and marking every single private field with it.
