### ISSUE TITLE
[Bug] `ValueTuple<T1, T2>` is not converted to links when using `"outputFormat": "mref"`

### ISSUE THREAD

**Issue by filzrev** [dotnet/docfx#10317]
**Describe the bug**

When using `"outputFormat": "mref"` setting.
`ValueTuple<T1, T2>` cref DocComment is not resolved to link.
 
**To Reproduce**

1. Initialize docfx project and configure to include C# source code.
2. Add following property to source code.
```csharp
   /// <summary>
   /// - <see cref="System.ValueTuple" />
   /// - <see cref="System.ValueTuple{T}" />
   /// - <see cref="System.ValueTuple{_}" />
   /// - <see cref="System.ValueTuple{T1,T2}" />
   /// - <see cref="System.ValueTuple{_,_}" />
   /// - <see cref="System.Collections.Generic.Dictionary{_,_}" />
   /// </summary>
   public static class DummyClass
   {
   }
```
3. Run `docfx metadata` command
4. Run `docfx build --serve` command and confirm generated HTML
5. Following cref links are rendered as plain text (`<span class="xref">(T1, T2)</span>`).
5.1. `<see cref="System.ValueTuple{T1,T2}" />` 
5.2. `<see cref="System.ValueTuple{_,_}" />` 

It seems caused by `SymbolDisplay.ToDisplayParts` Roslyn API returns custom `ImmutableArray<SymbolDisplayPart>` that don't contains `href` URL.

** Generated yaml for `ValueTuple<T1>`**
```yml
- uid: System.ValueTuple`1
  commentId: T:System.ValueTuple`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetuple-1
  name: ValueTuple<T1>
  nameWithType: ValueTuple<T1>
  fullName: System.ValueTuple<T1>
  spec.csharp:
  - uid: System.ValueTuple`1
    name: ValueTuple
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-1
  - name: <
  - name: T1
  - name: '>'
```

**Generated yaml for `ValueTuple<T1,T2>`  (href link is missing)**
```yml
- uid: System.ValueTuple`2
  commentId: T:System.ValueTuple`2
  name: (T1, T2)
  nameWithType: (T1, T2)
  fullName: (T1, T2)
  spec.csharp:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: )
  spec.vb:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: )
```

**Expected behavior**
`ValueTuple<T1,T2>` is rendered as link.
