### ISSUE TITLE
[Bug] `<see>` XML tag ends up points to page instead of element on page with corresponding id

### ISSUE THREAD

**Issue by cjsha** [dotnet/docfx#10322]
**Bug Description & Expected Behavior:*
`<see cref="ContextTask.AcquisitionClockHz"/>` in XML comment resolves to:
`<xref href="OpenEphys.Onix1.ContextTask.AcquisitionClockHz" data-throw-if-not-resolved="false"></xref>` in yaml which resolves to:
`<a class="xref" href="OpenEphys.Onix1.ContextTask.html">Acquisition<wbr>Clock<wbr>Hz</a>` in html instead of:
`<a class="xref" href="OpenEphys.Onix1.ContextTask.html#OpenEphys_Onix1_CreateContext_AcquisitionClockHz">Acquisition<wbr>Clock<wbr>Hz</a>`.

The effect of this is that users are linked to the page instead of the id on page that I want to direct user to.
For example, clicking on this hyperlink [AcquisitionClockHz](https://open-ephys.github.io/bonsai-onix1-docs/api/OpenEphys.Onix1.ContextTask.html)  on [this page](https://open-ephys.github.io/bonsai-onix1-docs/api/OpenEphys.Onix1.TS4231V1PositionDataFrame.html) should be [AcquisitionClockHz](https://open-ephys.github.io/bonsai-onix1-docs/api/OpenEphys.Onix1.ContextTask.html#OpenEphys_Onix1_CreateContext_AcquisitionClockHz) instead. Note that an html element with that particular id doesn't currently exist on that page, but it doesn't work when I add `id={{id}} data_uid={{uid}}` to an html element which I have done on a local branch.

What are the conditions that create the correct href value where the URL is appended with a \#mangled_uid? This is all done using a custom template, but I'm not sure how that might mess it up.

The repo where I am having this issue is here:
https://github.com/open-ephys/bonsai-onix1-docs

**Context (please complete the following information):**
- Browser: Firefox
- Form factor: desktop
- Docfx version: 2.77.0
- Template: custom

Thank you so much for your help.

**Comment by cjsha** [comment]
In other words, in the [`xrefmap.yml`](https://open-ephys.github.io/bonsai-onix1-docs/xrefmap.yml) file, how do I get
``` yaml
- uid: OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  name: AcquisitionClockHz
  href: api/OpenEphys.Onix1.ContextTask.html # undesired href value
  commentId: P:OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  fullName: OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  nameWithType: ContextTask.AcquisitionClockHz
```
to resolve as:
``` yaml
- uid: OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  name: AcquisitionClockHz
  href: api/OpenEphys.Onix1.ContextTask.html#OpenEphys_Onix1_ContextTask_AcquisitionClockHz # desired href value
  commentId: P:OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  fullName: OpenEphys.Onix1.ContextTask.AcquisitionClockHz
  nameWithType: ContextTask.AcquisitionClockHz
```
instead? 

Here is an example where something similar is being achieved:
``` yaml
- uid: Bonsai.Dsp.Decimate.Factor
  name: Factor
  href: api/Bonsai.Dsp.Decimate.html#Bonsai_Dsp_Decimate_Factor
  commentId: P:Bonsai.Dsp.Decimate.Factor
  fullName: Bonsai.Dsp.Decimate.Factor
  nameWithType: Decimate.Factor
```
on the [Bonsai docs site](https://bonsai-rx.org/docs/api/Bonsai.Dsp.DownsamplingMethod.html) that are also generated with docfx.
