### ISSUE TITLE
[Bug] Generic methods / types are not ordered correctly together with their non-generic versions

### ISSUE THREAD

**Issue by mikernet** [dotnet/docfx#10332]
**Describe the bug**
Title says it all. Examples:

![Image](https://github.com/user-attachments/assets/8040782d-2654-4b39-987d-ff5fb0fe7021)

![Image](https://github.com/user-attachments/assets/fdf0de37-63a3-4c66-ab3f-8dba72043e30)

**Expected behavior**
Generic types/methods should follow immediately after non-generic ones with the same name.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.77.0
- .NET version: .net 8

**Comment by filzrev** [comment]
It seems to be occurred when using `"outputFormat": "mref"` options.
When using `apiPage` or `markdown` options. It works as expected.

I though it's introduced by enabling `InvariantGlobalization` mode. (#8893)
I'll try to create PR to fix reported issue later.

**Background**
Currently toc items are sorted by `uid`.
And when item contains `generic type parameter` it's represented as "`1". 

But when toc items are sorted with `Ordinal` order.
The order of results is changed from what is expected.

**Sample TOC file**
```yaml
  - uid: BuildFromProject.IRoutedView
    name: IRoutedView
  - uid: BuildFromProject.IRoutedViewModel
    name: IRoutedViewModel
  - uid: BuildFromProject.IRoutedView`1
    name: IRoutedView<T>
```
