### ISSUE TITLE
[Bug] Template modern

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#10411]
**Describe the bug**
The disposition change in the web page.

**Build with 2.77.0 docfx**
![Image](https://github.com/user-attachments/assets/1b2e334d-ccd2-445e-aae4-78bb8f0e6c60)

**Same site with 2.78.1**
![Image](https://github.com/user-attachments/assets/35fafc8d-d158-4ffa-86b6-ea3958e058dd)

**Comment by filzrev** [comment]
I'm also confirmed. It can reproduce problems with project that is created by `docfx init --yes` command.

It seems [docfx.scss override setting](https://github.com/dotnet/docfx/blob/872fdb3ca80aa075a0a3653f0f370c0891b9097e/templates/modern/src/docfx.scss#L6-L9) is not applied on `v2.78.1`.
And bootstrap default styles are used.


**1.Excerpt of `docfx.min.css`(docfx 2.77.0)**
`max-width` value is overridden to `1768px` 

```css
@media (min-width: 1400px) {
    .container-xxl, .container-xl, .container-lg, .container-md, .container-sm, .container {
        max-width: 1768px
    }
}
```

**2.Excerpt of `docfx.min.css`(docfx 2.78.1)**
Bootstrap 5.3.3 default setting is used.

```css
@media (min-width: 576px) {
    .container-sm, .container {
        max-width: 540px
    }
}

@media (min-width: 768px) {
    .container-md, .container-sm, .container {
        max-width: 720px
    }
}

@media (min-width: 992px) {
    .container-lg, .container-md, .container-sm, .container {
        max-width: 960px
    }
}

@media (min-width: 1200px) {
    .container-xl, .container-lg, .container-md, .container-sm, .container {
        max-width: 1140px
    }
}

@media (min-width: 1400px) {
    .container-xxl, .container-xl, .container-lg, .container-md, .container-sm, .container {
        max-width: 1320px
    }
}
```
