### ISSUE TITLE
Dividers in Navbar defined in the TOS file

### ISSUE THREAD

**Issue by Nick-Lucas** [dotnet/docfx#1143]
It would be really helpful if you could define a divider in the TOS file, to separate out similar links.

This would look something like:
```
- name: Item 1
  href: item1/
- name: Item 2
  href: item2/
- divider
- name: Item 3
  href: item3/
```

### Example use case: 
separating off-site links from documentation links.

You can kind of fake it right now with an item like:
```
- name: " "
  href: /
```
however, this inserts a link, the vertical height is wrong, and when you're on the link it is a slightly darker black.
![image](https://cloud.githubusercontent.com/assets/8896153/21816885/b2c1c390-d759-11e6-9164-5991832a9d50.png)

**Comment by vicancy** [comment]
Prosposal: 
```yml
- name: Item 1
  href: item1/
- name: Item 2
  href: item2/
- name: "---"
- name: Item 3
  href: item3/
```

And modify https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js#L343 to transform "---" into "divider"
