### ISSUE TITLE
Different HTML name for an article.md

### ISSUE THREAD

**Issue by basitanwer** [dotnet/docfx#1310]
### Generate a different HTML for a different article file using TOC.yml

Is it possible that i can generate a different html file name for a different article file name? This is mostly useful for SEO purposes.

### Example

``` yml
- name: Introduction
      href: Introduction to Github.md
      htmlname: intro-to-github.html
```

Otherwise `%20` is inserted in the spaces in between.

for example: `Introduction%20to%20Github.html` is seen when accessed from browser
