### ISSUE TITLE
Exclude System.ObsoleteAttribute

### ISSUE THREAD

**Issue by bouboup** [dotnet/docfx#1657]
Hi,

I wanted to exclude members with [Obsolete] attribute.

Here is my filter config :
```
apiRules:
- exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute
    type: Member
```

It's not working, [Obsolete] methode are still in my Api Documentation.

I am missing something ?

Many thanks!

**Comment by hellosnow** [comment]
@ansyral according to http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html, should we use `attributeRules` instead of `apiRules` to filter out ObseloteAttribute?
```yaml
attributeRules:
- exclude:
    uidRegex: System\.ObsoleteAttribute$
    type: Type
```
