### ISSUE TITLE
Filter inherited members? (feature request)

### ISSUE THREAD

**Issue by mfaux** [dotnet/docfx#1780]
### Filter inherited members? (feature request)
I would like to filter inherited members. For example, `System.Object` produces a lot of 'noise', and distracts from more relevant documentation:

![image](https://user-images.githubusercontent.com/1324114/27287634-b7c687e4-5504-11e7-85d4-7ad462b11c7b.png)

**Comment by vicancy** [comment]
Hi @mfaux this can be done by adding a `filterConfig.yml` http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#3-default-filter-configuration
For example, the following excludes all the members inside "System.Object"
```yml
apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
```
You can also exclude one specific method, for example, the following exclude "System.Object.GetHashCode"
```yml
apiRules:
- exclude:
      uidRegex: ^System\.Object\.GetHashCode
      type: Member
```

**Comment by mfaux** [comment]
Fantastic, thank you 👍 .  Not sure how I missed that )

**Comment by lorddev** [comment]
Using the suggestion above I have created the following filterConfig.yml:
```
apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
- exclude:
      uidRegex: ^Microsoft\.AspNetCore\.Mvc\.Controller
      type: Type
```
But System.Object and Microsoft.AspNetCore.Mvc.Controller still show up in the inheritance section.
