### ISSUE TITLE
Error parsing filter config file

### ISSUE THREAD

**Issue by fsdthnk** [dotnet/docfx#1877]
### Title
**Error parsing filter config file**

### Functional impact
Metadata cannot be generated, thus a build is not possible.

### Minimal repro steps
1. Include this line into the config file, section metadata:
`"filter": "filterConfig.yml"`
2. Create a file named "filterConfig.yml" with the following content:
```
apiRules:
- include:
	uidRegex: ^Fsd\.HuaDataGenerator\.Application$
- exclude:
	uidRegex: ^Fsd\.HuaDataGenerator$
```
Alternatively, the following content produces the same result:
```
apiRules:
- include:
	uid: Fsd.HuaDataGenerator.Application
- exclude:
	uid: Fsd.HuaDataGenerator
```

### Expected result
Metadata generation without error.

### Actual result
The following error shows up:
[17-07-14 02:09:12.808]Info:Config file docfx.json found, start generating metadata...
[17-07-14 02:09:15.736]Error:Error extracting metadata for /src/HuaDataGenerator/HuaDataGenerator.csproj,/src/TestHuaDataGen/TestHuaDataGen.csproj: Error parsing filter config file filterConfig.yml: (Line: 3, Col: 1, Idx: 23) - (Line: 3, Col: 2, Idx: 24): While scanning for the next token, find character that cannot start any token.

**Comment by superyyrrzz** [comment]
@fsdthnk Seems it's not a valid YAML. Can you try replacing the starting TAB with 2 spaces like:
```yaml
apiRules:
- include:
  uid: Fsd.HuaDataGenerator.Application
- exclude:
  uid: Fsd.HuaDataGenerator
```

**Comment by vwxyzh** [comment]
@fsdthnk your filter logic maybe wrong.
I guess your code like following:
```cs
namespace Fsd.HuaDataGenerator
{
  public class Application { }
  public class Others { }
}
```
If you want to only filter `Fsd.HuaDataGenerator.Others`, you cannot exclude the namespace `Fsd.HuaDataGenerator`, it will also exclude `Fsd.HuaDataGenerator.Application`.

Filters apply by following way:
1. Check visible, if not, return exclude.
2. Apply parent API first, if excluded, return.
3. Apply this API:
    1. Apply rules one by one, if matched, return.
    2. return default (include).

For your case, I think you should write like following:
```yaml
apiRules:
- include:
  uidRegex: ^Fsd\.HuaDataGenerator\.Application$
- exclude:
  uidRegex: ^Fsd\.HuaDataGenerator\.
```

**Comment by fsdthnk** [comment]
@superyyrrzz Thanks for that hint (tabs are not allowed). I recommend to upgrade the parser, so that this tool accept tabs in configuration files. However, this solved the problem completely (see below).
@vwxyzh My code is structured in the following manner:
```
namespace Fsd.HuaDataGenerator
{
  public class Application { }
  public interface IHuaDevice { }
  public class HuaDevice { }
}

namespace TestHuaDataGen
{
  public class Program { }
}
```
Fsd.HuaDataGenerator is the main project generating a class library, TestHuaDataGen is just a test project for testing that library. I want to exclude class Fsd.HuaDataGenerator.HuaDevice and all classes in namespace TestHuaDataGen. Unfortunately, this code does not work. I do not get any error, however nothing is excluded in the generated api document:
```
apiRules:
- include:
  uid: Fsd.HuaDataGenerator.Application
  uid: Fsd.HuaDataGenerator.IHuaDevice
- exclude:
  uid: Fsd.HuaDataGenerator.HuaDevice
  uidRegex: ^TestHuaDataGen\.
```
Any comment?

**Comment by vwxyzh** [comment]
@fsdthnk 
Just find a mistake in my example:
```yaml
apiRules:
- include:
    uidRegex: ^Fsd\.HuaDataGenerator\.Application$
- exclude:
    uidRegex: ^Fsd\.HuaDataGenerator\.
```
`uidRegex` is a property for `include` or `exclude`.

**Comment by fsdthnk** [comment]
@vwxyzh Also this code does not work:
```
apiRules:
- include:
  uidRegex: ^Fsd\.HuaDataGenerator\.Application$
  uidRegex: ^Fsd\.HuaDataGenerator\.IHuaDevice$
- exclude:
  uidRegex: ^Fsd\.HuaDataGenerator\.HuaDevice$
  uidRegex: ^TestHuaDataGen\.
```
See screenshot below:
![screenshot](https://user-images.githubusercontent.com/30116834/28265408-d3534636-6aef-11e7-8a09-b680787e4f50.jpg)
