### ISSUE TITLE
Skip obsolete methods when generating metadata

### ISSUE THREAD

**Issue by PhilipCotan** [dotnet/docfx#2068]
Hi there, 

I was wondering if there's a way to skip some methods when generating documentation.
Let's  say I want to generate documentation for my API and I want to skip some methods in a source code file. Is that possible?

Thank you,
Philip

**Comment by superyyrrzz** [comment]
You can try this: http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html
```yml
attributeRules:
- exclude:
    uidRegex: ^System\.Obsolete$
```
