### ISSUE TITLE
[Question] Can I generate Documentation from Source (.vb or vbproj) with VS 2015

### ISSUE THREAD

**Issue by cropper1991** [dotnet/docfx#2094]
I've noticed that in the guidelines, there are comments saying that Visual Studio 2017 is a pre-requisite for building documentation, but I was wondering, if I'm only providing .vb or .vbproj files whether this is supported at all?

Currently I keep getting Null Reference Exceptions during the Metadata Gathering Phase.

**Comment by cropper1991** [comment]
Ignore this as I've got around these issues (was due to MSBuild Version being incorrect on the vbproj files). Now I'm encountering issues with the filtering mechanism. What I am basically trying to do is exclude all types except for the following two regex strings:
WCF.HTTPLayer
Elements

Is this doable in the filtering mechanism?

**Comment by vwxyzh** [comment]
@cropper1991 yes, you can add two include first, then add exclude all types.
e.g.:
```yaml
- include:
    uidRegex: ^WCF\.HTTPLayer
    type: Type
- include:
    uidRegex: ^Elements
    type: Type
- exclude:
    uidRegex: .*
    type: Type
```

See [document](http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#the-format-of-the-filter-configuration-file).
