### ISSUE TITLE
[Question] How to customize/hide content in API documentation?

### ISSUE THREAD

**Issue by andreycha** [dotnet/docfx#2254]
Hi.
We introduce API documentation in our systems and would like to strip out some of the information. We have POCO classes, so basically we don't need following information:

- `Inheritance` chain
- `Implements` block
- `Inherited Members` block
- `Syntax` for classes
- `Property Value` block
- `Declaration` for members

I was able to exclude some of this information (namely members inherited from `System.Object` and `Implements` information for system interfaces) using filter config:

```
apiRules:
- exclude:
    # inherited Object methods
    uidRegex: ^System\.Object\..*$
    type: Method
- exclude:
    # mentioning types from System.* namespace
    uidRegex: ^System\..*$
    type: Type
```

But how can I exclude the rest? As far as I understand post processor only works with global metadata and already generated html files. Is there a way to control metadata generation?

I guess I can also customize default template to hide particular divs in html, but that feels like a workaround.

Thank you.

**DocFX Version Used**: 2.28

**Template used**: default
