### ISSUE TITLE
Metadata APIs using incorrect URL - using the dest folder path instead

### ISSUE THREAD

**Issue by Shazwazza** [dotnet/docfx#2343]
**DocFX Version Used**: 

v2.29

**Template used**: (`default` or `statictoc` or contain custom template)

custom 

**Steps to Reproduce**:

1. clone this PR https://github.com/apache/lucenenet/pull/206 
2. run the powershell build `docs.ps1 1 1` in folder `apidocs` 
3. browse to localhost:8080
4. see the URL used for the API docs uses the path configured for the "dest" parameter in the docfx.json file for the metadata
![image](https://user-images.githubusercontent.com/1742685/34313122-2a5f0470-e7bd-11e7-8714-88e69b143416.png)

**Expected Behavior**:

The URL for the APIs should be (for example) `http://localhost:8080/api/Lucene.Net/Lucene.Net.Analysis.html`

**Actual Behavior**:

The URL for the APIs is (for example)
`http://localhost:8080/api/obj/docfx/api/Lucene.Net/Lucene.Net.Analysis.html` instead of `http://localhost:8080/api/Lucene.Net/Lucene.Net.Analysis.html`

NOTES: 

I understand that this project and build setup is fairly complicated and this is due to how the Lucene.NET project is setup with it's docs (since it's essentially a mirror of the java Lucene project). We use a lot of "overwrite" files for namespace documentation too. 

I suspect the problem lies with how the toc is built. For example, here's the definition for one of the csproj's in the docfx.json file:

```json
"src": [
  {
    "files": [
      "Lucene.Net/Lucene.Net.csproj",
      "Lucene.Net.Misc/Lucene.Net.Misc.csproj"      
    ],
    "exclude": ["**/obj/**", "**/bin/**", "**/Lucene.Net.Test*/**"],
    "src": "../src"
  }
],
"dest": "obj/docfx/api/Lucene.Net",
"properties": {
    "TargetFramework": "netstandard1.6"
}
```

which follows the examples listed in the docfx documentation and seems to build fine. Then our "content" section build looks like 

```json
"content": [
      {
        "files": ["api/**.yml","api/**.md","obj/docfx/api/**"],
        "dest": "api"
      },
      {
        "files": ["toc.yml", "*.md"]
      }
    ],
```
The problem most likely is here in the "api/toc.yml" file which we have this listed (for example):

```yml
- name: Lucene.Net
  href: ../obj/docfx/api/Lucene.Net/toc.yml
  topicUid: Lucene.Net
- name: Lucene.Net.Queries
  href: ../obj/docfx/api/Lucene.Net.Queries/toc.yml
  topicUid: Lucene.Net.Queries
```

However, if we don't use those "href" and instead just try topicUid like:

```yml
- name: Lucene.Net
  topicUid: Lucene.Net
- name: Lucene.Net.Queries
  topicUid: Lucene.Net.Queries
```

this no longer works and doesn't include the generated toc items.  

The docfx docs mention both topicHref and topicUid but the topicHref docs also mention an undocumented item: `tocHref`, I'm wondering if there's just something I'm missing with this whole setup?

We've been working on this docs project for quite some time and we've always kept up with the latest versions of docfx and we have noticed bugs being fixed but I'm fairly sure that quite a while ago, these URLs were actually working with this same configuration.

Any help, advise or tips is much appreciated!
