### ISSUE TITLE
Exclude System.ObsoleteAttribute with generic ctor target?

### ISSUE THREAD

**Issue by Herve-M** [dotnet/docfx#2451]
**DocFX Version Used**: 2.31.0.0

**Template used**: `default` 

**Steps to Reproduce**:
The problem is how to exclude an attribute with any arg.?
In my case I have an interface with generic, with ObsoleteAttribute, and an class who implement it with ObsoleteAttribute too, But I don't get the method to be ignored/not displayed...

1. Create an Interface + Class, having an method with ObsoleteAttribute (with message)
```
public interface ITest<Tx> where Tx: class {
    [Obsolete("Some text")]
    ITest<Tx> GetFoo()
}
```
```
public class Test<Tx> : ITest<Tx> {
    [Obsolete("Some text bis")]
    public virtual ITest<Tx> GetFoo()
}
```
2. Add apiRule: 
```
- exclude:
      hasAttribute:
        uidRegex: ^System\.ObsoleteAttribute$
        ctorNamedArguments:
          message: "**"
```
3. build / serve

**Expected Behavior**:
`ITest<Tx> GetFoo()`  shouldn't be displayed 

**Actual Behavior**:
`ITest<Tx> GetFoo()` is displayed

**Comment by vwxyzh** [comment]
@Herve-M try following filter:
```yaml
- exclude:
      hasAttribute:
        uidRegex: ^System\.ObsoleteAttribute$
```

**Comment by Herrmel** [comment]
@Herve-M did you get it to work? I just can't even though I tried every possible configuration I could imgaine xS

**Comment by Herve-M** [comment]
@Herrmel No.. The version of vwxyzh do nothing.. I think the attribut is ignored or even not parsed. The message one is included as code directly at first sight,

**Comment by Herrmel** [comment]
@vwxyzh Could you have a look at this?

**Comment by Herrmel** [comment]
@vicancy Could you have a look at this?

**Comment by vwxyzh** [comment]
Let me take a look.

**Comment by vwxyzh** [comment]
@Herve-M @Herrmel ,
There are two issues:
1. filter yaml should be following:
    ```yaml
    - exclude:
        hasAttribute:
          uid: System.ObsoleteAttribute
    ```
2. There is a bug for filter attribute without arguments values, I will create an PR to fix it.
