### ISSUE TITLE
Only generate wanted API's via attributes

### ISSUE THREAD

**Issue by dnperfors** [dotnet/docfx#2473]
**DocFX Version Used**: 2.32

**Template used**: default

We are trying to document our 'published' api, which basically means all public members that are marked with a `PublishedAttribute` attribute. However I don't seem to be able to generate the correct filters for it. 
Consider the following class:
```
namespace Project.MyNameSpace
{
    [Published]
    public class PublishedClass
    {
        [Published]
        public string PublishedMember { get; set; }

        public string NotPublishedMember { get; set; }
    }
}
```
In this case I only want documentation of `PublishedClass` and of `PublishedClass.PublishedMember`. 

I was thinking in the terms of the following filter file:
```
apiRules
- include:
      hasAttribute:
        uid: Project.PublishedAttribute
- exclude:
      uidregex: ^Project
      type: Type
```
The problem is that `NotPublishedMember` is shown in the documentation.

Is there any way to get this kind of behaviour? or should there be something like a `not` filter be added?

**Comment by dnperfors** [comment]
Never mind, I figured it out. The exclude will exclude the namespace containing the API as well, so the following config does work:
```
apiRules
- include:
      hasAttribute:
        uid: Project.PublishedAttribute
- exclude:
      uidregex: ^Project
      type: Type
```

**Comment by dnperfors** [comment]
Trying out a lot of things does work, with the following filter I seem to have the correct behaviour:
```
apiRules:
- include:
    hasAttribute:
        uid: Project.PublishedAttribute
    type: Member
- exclude:
    type: Member
- include:
    hasAttribute:
        uid: Project.PublishedAttribute
    type: Type
- exclude:
    type: Type
```
