### ISSUE TITLE
Template not working on node2docfx yml generated files 

### ISSUE THREAD

**Issue by lipedeitos** [dotnet/docfx#2474]
**DocFX Version Used**:  2.31.0

**Template used**: statictoc

**Steps to Reproduce**:

1. Got plenty of .md files inside "articles" folder.
2. Got node2docfx installed and configured, .yml files are generated in my "api" folder as expected:
```
### YamlMime:UniversalReference
items:
  - uid: ffdocs.Test
    id: ffdocs.Test
    name: Test
    summary: Test class description
    fullName: ffdocs.Test
    type: Class
    children:
      - 'ffdocs.Test.#ctor'
    langs:
      - js
  - id: 'ffdocs.Test.#ctor'
    uid: 'ffdocs.Test.#ctor'
    parent: ffdocs.Test
    name: Test()
    fullName: ffdocs.Test.Test()
    summary: ''
    type: Constructor
    syntax:
      content: new Test()
    langs:
      - js
```
3. Until now i have an "articles" and "api" folder with .md and .yml files
4. Open my  statictoc template add "abc" to the beginning of the body tag on _master.tmpl
5. Run docfx build command and everything looks fine, all .md and .yml turn into .html files
6. The .md files turn into html files an the changes made in statictoc are there.
7. **The problem** is that .yml files generated by node2dofx turn into html files but the changes made in statictoc **are not there**. It applies another template.

**Expected Behavior**:
Template must be applied equaly in all files built

**Actual Behavior**:
 The .yml files generated by node2docfx turn into html files but the changes made in statictoc **are not there**. It applies "another" template that i don't have any idea where it is, or where i can change it.
