### ISSUE TITLE
YML generation for constants omit value in syntax for C#

### ISSUE THREAD

**Issue by aienabled** [dotnet/docfx#252]
Hello!

I'm using docfx version 1.7.1 with default template.

Example:
```c#
public const ushort Test = 123;
```

Result (YML):
```yml
 syntax:
    content: public const ushort Test
    content.vb: Public Const Test As UShort = 123
```

So in generated HTML the value of Test constant is omitted.

Regards!
