### ISSUE TITLE
Main nav bar does not collapse when items are added to the dropdown

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#2544]
**DocFX Version Used**: 2.32.2

**Template used**: (`default` or `statictoc` or contain custom template) default + custom

**Steps to Reproduce**:

1. Add dropdown items to the main nav bar
```yml
- name: Guides
  href: articles/
- name: API
  items:
  - name: REST API
    href: restapi/
  - name: Plugins
    href: obj/api/
```
**Expected Behavior**: In this example, the nav bar would expand when you hover over "API"

**Actual Behavior**: The "dropdown" items are permanently stacked in an open position

![2018-03-22 16_43_46-microsoft edge](https://user-images.githubusercontent.com/15255009/37802666-0d5f5d82-2df1-11e8-8832-409249241d44.png)

Thank you.
