### ISSUE TITLE
Section of Markdown files at top of left-side nav bar for API documentation page

### ISSUE THREAD

**Issue by cedar-ave** [dotnet/docfx#2545]
**DocFX Version Used**: 2.32.2

**Template used**: (`default` or `statictoc` or contain custom template) default + custom

Is it possible to add articles in the left-side nav bar of a page of API documentation? This is a mockup:

![2018-03-22 16_53_14-namespace microsoft docascode _ docfx website](https://user-images.githubusercontent.com/15255009/37803317-b1dedee4-2df3-11e8-8814-5b3188fe1d30.png)

Thank you

**Comment by vicancy** [comment]
Yes you can with the help of http://dotnet.github.io/docfx/tutorial/intro_toc.html#link-to-another-toc-file, following these steps, take docfx-seed repo as an example
1. Add a folder and create a toc.yml, e.g. `fusion/toc.yml` with content:
```yml
- name: Concetputal
  href: ../articles/toc.md
- name: Reference
  href: ../obj/api/toc.yml
```
2. Update the root toc.yml, change the API reference `href: obj/api/` to `href: fusion/`:
```yml
- name: Home
  href: index.md
- name: Articles
  href: articles/
  homepage: articles/docfx_getting_started.md
- name: API Documentation
  href: fusion/
- name: REST API
  href: restapi/
```
3. Add fusion folder to docfx.json:
```json
...
"content": [
  { 
    "files": "fusion/**"
  }
]
```
4. The generated page is as:
![image](https://user-images.githubusercontent.com/668244/37807281-9209be5e-2e7f-11e8-8cc2-864de3a95e79.png)
