### ISSUE TITLE
Enable external link for parameter types, return types and property value types.

### ISSUE THREAD

**Issue by jsntcy** [dotnet/docfx#256]
Taking the following return type as example, when the user click "IRandomAccessStream", it should navigate him to the page "https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.streams.irandomaccessstream.aspx".

```yaml
return:
   type: w_storage_streams.irandomaccessstream

- uid: w_storage_streams.irandomaccessstream   
  href: https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.streams.irandomaccessstream.aspx   
  name: IRandomAccessStream
```
