### ISSUE TITLE
Can't show fields inherited from generic base classes using a custom template for the class page

### ISSUE THREAD

**Issue by svver** [dotnet/docfx#276]
I'm trying to show inherited methods, fields and properties on the class description page using the data contained in `inheritedMembers` block of .yml files describing class metadata. I created a custom template that overrides `class.tmpl.partial` and adds the following code (almost the same as for the inheritance hierarchy): 
```
{{#inheritedMembers.0}}
<div class="inheritance">
  <h5>Inherited members</h5>
{{#inheritedMembers}}
    <div class="level{{index}}">{{{specName.0.value}}}</div>
{{/inheritedMembers}}
    
</div>
{{/inheritedMembers.0}}
```
You can see the sample in [this repo] (https://github.com/sergey-vershinin/docfx-issues/tree/master/inheritedMembers).

Almost everything works well except for the fields that are inherited from a generic base class. Those are shown as a plain text (not links). Note that the methods inherited from the same generic class are shown as expected. Is this a bug? 
![image](https://cloud.githubusercontent.com/assets/8723144/14744962/6c577c1c-08c2-11e6-88b7-dcdaf0587e7c.png)

**Comment by vwxyzh** [comment]
it seems good in yaml.
I think we should not use `{{{specName.0.value}}}` for inherited members, but we don't have an easy way to bind them in template.
we need such an xref link to definition (in this case: ``FooLib.BaseGenericFooClass`1.BaseGenericClassField``) and display with spec name/fullname.

```yaml
- uid: FooLib.BaseGenericFooClass{System.Object}.BaseGenericClassField
  parent: FooLib.BaseGenericFooClass{System.Object}
  definition: FooLib.BaseGenericFooClass`1.BaseGenericClassField
  name: BaseGenericClassField
  fullName: FooLib.BaseGenericFooClass<System.Object>.BaseGenericClassField
  fullname.vb: FooLib.BaseGenericFooClass(Of System.Object).BaseGenericClassField
- uid: FooLib.BaseGenericFooClass`1.BaseGenericClassField
  parent: FooLib.BaseGenericFooClass`1
  isExternal: false
  name: BaseGenericClassField
  fullName: FooLib.BaseGenericFooClass<T>.BaseGenericClassField
  fullname.vb: FooLib.BaseGenericFooClass(Of T).BaseGenericClassField
```

**Comment by sergey-vershinin** [comment]
@vwxyzh, do you mean that `inheritedMembers` in YAML-files will look like those you've shown? 

As for the `{{{specName.0.value}}}`, that was just a copy-paste because there is no docs about the model being rendered by templates. Is it possible to log that model to a file?

**Comment by vwxyzh** [comment]
I mean `specName` is used for class, e.g. `List<string>` has four parts:
- `List` link to ``System.Collection.Generic.List`1``
- `<` literal
- `string` link to `System.String`
- `>` literal
But for inherited members this behavior is strange.
e.g. `BaseClassMethod(System.Int32)` should only contain one part, it link to the method `BaseClassMethod(System.Int32)`.
If use `specName`, it will be 4 part:
- `BaseClassMethod` link to the method `BaseClassMethod`
- `(` literal
- `System.Int32` link to the structure `System.Int32`
- `)` literal

**Comment by vwxyzh** [comment]
For short term, @superyyrrzz please provide a template sample.

For long term, I suppose to use `definition` as alias.
e.g.: following reference 
```yaml
- uid: Foo
  prop1: Overridden
  definition: Bar
- uid: Bar
  prop1: Bar1
  prop2: Bar2
```
will be resolved same as
```yaml
- uid: Foo
  prop1: Overridden
  prop2: Bar2
```
@vicancy @chenkennt any idea?
