### ISSUE TITLE
azure-docs-pr: Schema document with markdown field should not check for heading block

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3328]
Schema:
```csharp
    [PageSchema]
    public class TestPage
    {
        [Markdown]
        public string Description { get; set; }

        [InlineMarkdown]
        public string InlineDescription { get; set; }
    }
```

Input:
```yaml
#YamlMime:TestPage
description:
inlineDescription: >
  This is a list:
    - Item 1
    - Item 2
    - `Item 3`
    
  ## Not heading
```
Output:
```
heading-not-found test/f1/a.yml(0,0): The first visible block is not a heading block with `#`
```

Expected:
No warning for heading-not-found
