### ISSUE TITLE
Cannot selective include types in API filter

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#3380]
**DocFX Version Used**: 2.39.1.0

**Template used**: `default`

I would like to write an `apifilter.yml`  where all types (interfaces, classes) and namespaces should be _excluded_ unless explicitly _included_ in the filter.  

Consider the following structure:

```
namespace Classlibrary.Namespace1
{
    public class PublicClass1 
    {
        public void Foo(System.Double value) { }
    }
    public class PublicClass2 {}
    public interface IPublicInterface1 {}
    public interface IPublicInterface2 {}
}
namespace Classlibrary.Namespace2
{
    public class PublicClass1 {}
    public class PublicClass2 {}
    public interface IPublicInterface1 {}
    public interface IPublicInterface2 {}
}
```

So for my filter I would like to formulate the rule:

> Include only `Classlibrary.Namespace1.PublicClass1` , `public interface IPublicInterface1` and `Classlibrary.Namespace2` and exlcude everything else. Even if new types are added later, always exclude those new ones. Of course, types that come from the .NET framework like `System.Double` above should be correctly resolved.

This is the `apifilter.yml` I naively thought would do exactly that:

```
apiRules:
- include:
      uidRegex: ^ClassLibrary\.Namespace1.\.IPublicInterface1$
      type: Interface
- include:
      uidRegex: ^ClassLibrary\.Namespace1.\.PublicClass1$
      type: Class
- include:
      uidRegex: ^ClassLibrary\.Namespace2$
      type: Namespace
- exclude:
      uidRegex: .*
      type: Namespace
```

But it doesn't work. This will include only `Classlibrary.Namespace2` but not the two types from `Classlibrary.Namespace1` that where explicitly mentioned to be included.

I tried a lot of different filter combinations, none of which yielded the desired result.

**Comment by txwizard** [comment]
This past weekend, while constructing the API documentation that I just posted, I encountered a similar issue. In my case, the projects that I wanted to exclude were lab projects, so I zipped them up, and deleted them from the main directory tree. Nevertheless, I think the issue of marking a project for exclusion merits serious consideration. Perhaps something along the lines of a .gitignore file is needed, such as the copycat ignore files used by such things a the Laravel framework for PHP, NPM, and others. I have directories that house multiple "ignore" files along with their regular contents, and I've become accustomed to ignoring or leveraging them as appropriate.

**Comment by bitbonk** [comment]
@txwizard one way to achieve that could be to mark the types (or may it even works at assembly level) in your lab projects with an attribute e.g. ˋ[EditorBrowsable(EditorBrowsableState.Never)]ˋ and then Filter by attribute:

ˋˋˋ
- exclude:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never
ˋˋˋ

The best solution to your problem would be if it was possible to exclude a whole assembly or file in the API filter.

**Comment by superyyrrzz** [comment]
It workes with the following config:
``` yml
apiRules:
- include:
      uidRegex: ^ClassLibrary\.Namespace1\.IPublicInterface1$
      type: Interface
- include:
      uidRegex: ^ClassLibrary\.Namespace1\.PublicClass1$
      type: Class
- exclude:
      uidRegex: ^ClassLibrary\.Namespace1\..*$
      type: Type
- include:
      uidRegex: ^ClassLibrary\.Namespace1$
      type: Namespace
- include:
      uidRegex: ^ClassLibrary\.Namespace2$
      type: Namespace
- exclude:
      uidRegex: .*
      type: Namespace
```

Some notes:
1. The regex is case sensitive, so ensure to unify `Classlibrary` in your code and `ClassLibrary` in your config.
2. As mentioned in the [api filter document](https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html#1-api-filter-rules):
    > If a namespace is excluded, all types/members defined in the namespace would also be excluded. If a type is excluded, all members defined in the type would also be excluded.

    So you need to explicitly include Namespace1 in config, at the same time exclude all other types (classes, interfaces) in it:
    ``` yml
    - exclude:
          uidRegex: ^ClassLibrary\.Namespace1\..*$
          type: Type
    - include:
          uidRegex: ^ClassLibrary\.Namespace1$
          type: Namespace
    ```
