### ISSUE TITLE
vnext versioning dev spec

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3507]
# Phase 1

In phase 1, we still use DHS to do fallback, so we need output the same content as v2.
we are going to support:

1. All in one config:  
    A sample config file:
    ```yml
        name: dotnet
        content: "articles/**.{md,yml}"
        monikerRange:
            "articles/v1.0/**.{md,yml}": "netcore-1.0 || < netcore-2.0"
            "articles/v2.0/**.{md,yml}": ">= netcore-2.0"
        routing:
            "articles/v1.0/": "articles/"
            "articles/v2.0/": "articles/"
        monikerDefinitionUrl: "https://api.docs.com/monikers/"
    ```

2. No group, all files is built in one round.

## Scenarios supported

- Be able to handle small variations in content between versions, by augmenting existing documents with versioned content zones.
- Be able to handle one-shot, topic divergence by allowing specific articles to exist in multiple group, where the appropriate file is selected by version.
- Be able to express version constraints using a range-based syntax so that I don't have to encode every moniker in every document.
- Do not have to supply any versioning information if the article applies to all versions of a product.
- Be able to handle small variations in ToCs by allowing the system to annotate ToC nodes automatically with moniker data based on the article and docset metadata.

## What we need to do

1. Restore moniker definition file and evaluate moniker expression

    > The information that moniker definition need to contains:  
    > a. ordered moniker list  
    > ...?

3. Build files with monikers info.
    a. When loading a `page` type file to an input model, we need to contain the monikers info in this model.
    b. support zone syntax

4. Output  
    1. output structure  
        - When the moniker range is empty, the output should be `{outputFolder}/{locale}/{AssertID}`
        - When the moniker range is not empty, the output should be `{outputFolder}/{locale}/{monikerList}/{AssetID}`(monikerList is `string.Join(monikerList, ',')`)
    2. Reference resolve result:  
        1. link:
            - internal link: resolved to relative site path without query `?view={moniker}`.
            - external link: keep what it is.

        2. Xref:
            - internal Xref: resolved to relative site path without query `?view={moniker}`.
            - external Xref: keep what it is.

    3. Content:
        1. Output of `page` type file:
            ```json
                {
                    ...,
                    "monikers":
                    [
                        "moniker1",
                        "moniker2"
                    ]
                    ...,
                }
            ```
            the `monikers` contains all the monikers this file contains.
        2. Output of Toc:
            ```json
                {
                    ...,
                    {
                        "toc_title": "title",
                        "monikers": [
                            "moniker1",
                            "moniker2"
                        ],
                        "children": [...]
                    }
                    ...,
                }
            ```
        3. Output of .manifest.json:
            ```json
                {
                    "siteUrl":"/a",
                    "outputPath":"a.json",
                    "sourcePath":"a.md",
                    "monikers": [
                        "moniker1",
                        "moniker2"
                    ]
                }
            ```

## Challenges/Limitations

1. Not mutually exclusive moniker range

    Sample:
    ```
        |- articles/
        |    | - v1.0/
        |        |- a.md
        |    | - v2.0/ 
        |        |- a.md
        |    | - V3.0/
        |        | - c.md
        |- config.yml
    ```
    The moniker range of `articles/v1.0` is `netcore-1.0 || < netcore-2.0`  
    The moniker range of `articles/v2.0` is `>= netcore-2.0`  
    The moniker range of `articles/v3.0` is `>= netcore-1.0`  

    We do not accept this config:

    ```yml
        name: dotnet
        content: "articles/**.{md,yml}"
        monikerRange:
            "articles/v1.0/**.{md,yml}": "netcore-1.0 || < netcore-2.0"
            "articles/v2.0/**.{md,yml}": ">= netcore-2.0"
            "articles/v3.0/**.{md,yml}": ">= netcore-1.0"
        routing: 
            "articles/v1.0/": "articles/"
            "articles/v2.0/": "articles/"
            "articles/v3.0/": "articles/"
        monikerDefinitionUrl: "https://api.docs.com/monikers/"
    ```

    Because the moniker range is not mutually exclusive with others. so the config should be:

    ```yml
        name: dotnet
        content: "articles/**.{md,yml}"
        monikerRange:
            "articles/v1.0/**.{md,yml}": "netcore-1.0 || < netcore-2.0"
            "articles/v2.0/**.{md,yml}": ">= netcore-2.0"
            "articles/v3.0/**.{md,yml}": ["netcore-1.0 || < netcore-2.0", ">= netcore-2.0"]
        routing: 
            "articles/v1.0/": "articles/"
            "articles/v2.0/": "articles/"
            "articles/v3.0/": "articles/"
        monikerDefinitionUrl: "https://api.docs.com/monikers/"
    ```

    The ideal output of v3 should be:

    ```
        |- articles/
        |    | - netcore-1.0,netcore-1.1/
        |        | - a.json
        |    | - netcore-2.0,netcore-3.0/
        |        | - a.json
        |    | - netcore-1.0,netcore-1.1,netcore-2.0,netcore-3.0/
        |        | - c.json
    ```

    The build content of c.json should be:

    ```json
        {
            ...,
            "monikers":
            [
                "netcore-1.0",
                "netcore-1.1",
                "netcore-2.0",
                "netcore-3.0"
            ]
            ...,
        }
    ```

    In the legacy convert step, we will:
    1. Copy the build result of folder `v3.0`, the output should be :

    ```
    |- articles/
    |    | - netcore-1.0,netcore-1.1/
    |        | - a.json
    |        | - c.json
    |    | - netcore-2.0,netcore-3.0/
    |        | - a.json
    |        | - c.json
    ```

    And the monikers in each copy should be:
    ```json
        // netcore-1.0,netcore-1.1/c.json
        {
            ...,
            "monikers":
            [
                "netcore-1.0",
                "netcore-1.1"
            ]
            ...,
        }

        // netcore-1.0,netcore-1.1/c.json
        {
            ...,
            "monikers":
            [
                "netcore-2.0",
                "netcore-3.0"
            ]
            ...,
        }
    ```

2. Resolve Xref:

    In v2, each group will build one round, and in each group, there should be not be two files with the same uid, so the xref can be resolved correctly.  
    But in v3, there is no group, all files will be built in one round, so there will be two file with same uid but different version, which is not acceptable, and we have to handle this case.  
    To handle this, we have to contains the moniker range of each uid when we are generating the internal xref map.

    > group by uid and merge the moniker range?  
    > what if two file with same uid but different asset id?

3. Add monikers info in the TOC build result.
    To support selecting moniker on Toc, we have to contains monikers info of each Toc node.  
    Get rid of the empty page, we can get all file's monikers by quick scanning in the pre-build step.

4. Empty page
    when there is a file contains a moniker, but no content is included in this moniker, there will be a empty page when user view this file with this moniker.

    Here is a sample:
    The moniker list is v1.0 v2.0 v3.0
    ```markdown
    ---
    monikerRange: ">= v1.0"
    ---

    ::: moniker range=">= v2.0"

    content for `>= v2.0`

    ::: moniker-end

    ```

    when user view this page with url `{page_url}?view=v1.0`, the page will be empty.

    To resolve this, there are some works to do:  
    1. Remove this moniker from the moniker range from this file's build result.
    2. Remove this moniker from the moniker range of this file in the Toc.
    3. Remove this moniker from the moniker range of this file in the Xref map.

    After doing this  
    1. User can not see this file in the Toc when they choice the moniker v1.0.
    2. If user access url `{page_url}?view=v1.0`, the DHS will fallback to `{page_url}?view=v2.0`

    > Consider of the empty page, the Toc file will depend on the build result of each file. we can :  
    > 1. Build TOC after all other files build finished
    > 2. Fix the Toc build result when detecting empty page.

# Phase 2

In phase2, we are going to support:

1. Cross version reference

    User can reference to a file/Uid with specific version, and a warning should be reported if the file/Uid does not contains this version.

2. Bookmark validation with moniker info.

## Scenarios supported

- Be able to link to a file in the same group by relative path with query `?view={moniker}`, a warning should be reported if the file does not contains this moniker.  
- Be able to link to a file in different group by relative path with query `?view={moniker}`, a warning should be reported if the file does not contains this moniker.  
- Be able to reference a internal Uid with query `?view={moniker}`, a warning should be reported if the Uid does not contains this moniker.
- Be able to reference a external Uid with query `?view={moniker}`, a warning should be reported if the Uid does not contains this moniker.

# Phase 3

In phase 3, we are going to support:

1. Fallback logic to report fallback as a warning in build.

# Phase 4

In phase 4, we are going to support:

1. Generating pure `static` website.
