### ISSUE TITLE
Links to the same image with different casing produces non-deterministic result

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3540]
When two markdown files references the same image with different casing on windows, the result is non-deterministic.

```yaml
inputs:
  docfx.yml:
  docs/a.md: '![](image.png)'
  docs/b.md: '![](IMAGE.png)'
  docs/image.png:
outputs:
  output/a.json:
  output/b.json:
  output/image.png:
  build.manifest:
```

One possible solution is to use https://github.com/dotnet/corefx/issues/1086 but that is not shipped yet. 

Another practical solution is to provide an option to lowercase all links, which also matches v2 behavior.
