### ISSUE TITLE
Side Navigation Broken with 2.40.2

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#3606]
**DocFX Version Used**: 2.40.2

**Template used**: (`default` or `statictoc` or contain custom template) statictoc

**Steps to Reproduce**:

1. docfx init
2. repalce toc.yml content in articles folder by
```
- name: Sub Introduction
- name: Introduction
  items:
  - name: Introduction 1
    href: intro.md
  - name: Introduction 2
    href: intro.md
  - name: Introduction 3
    href: intro.md

```
3. docfx --template statictoc

**Expected Behavior**:
Nice Side Navigation on Articles page

**Actual Behavior**:
Strange Scrollbar and layout of items in navigation

Works with 2.39.2 or 2.40.2 with default template

**Comment by superyyrrzz** [comment]
From the sample in #3536 , try add ` dropdown: true`:

```yml
- name: Sub Introduction
- name: Introduction
  dropdown: true
  items:
  - name: Introduction 1
    href: intro.md
  - name: Introduction 2
    href: intro.md
  - name: Introduction 3
    href: intro.md
```
