### ISSUE TITLE
conceptual versioning in v3

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3607]
[Dev spec](https://github.com/dotnet/docfx/blob/v3/docs/designs/conceptual-versioning.md)
# Phase 1 Tasks:
- [x] Support setting `monikerRange` and `monikerDefinitionUrl` in config. (@928PJY )
- [x] Support setting `monikerRange` in yaml header. (@live1206 )
- [x] Support `moniker zone` syntax in conceptual markdown file (@928PJY )
- [x] Internal Xref map with moniker info (@live1206 )
- [x] Input/output mapping (@928PJY )
- [x] File output content
    - [x] Legacy output(@live1206 )
    - [x] Conceptual file
    - [x] Redirection file (@928PJY )
    - [x] Toc file(@928PJY )
- [x] Build manifest file(@live1206 )
- [x] ~~Blank page support ?~~
- [x] API to get moniker definition file (@928PJY )
    - Convert the output of current API `/v2/monikertrees/allfamiliesproductsmonikers` to our expected model
    - Add two config items to global config in `Docs.Build`:
    ```
    monikerDefinition: https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers
    http:
        https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers:
            headers:
                X-OP-BuildUserToken: xxxx-xxxxx
    ```
- [ ] Impact repo test & migration tool support (@928PJY )
![pipeline](https://user-images.githubusercontent.com/17958546/48385749-af455780-e72a-11e8-9372-ab69794b1c59.jpg)

# Dependencies
- [ ] Support publishing with overlapping monikerRange to DHS.
- [x] Publish with the new manifest file(depend on the new manifest design & implementation).

# Remaining work after phase1:
- [ ] Reference validation:
    - [x] refenrece to internal uid with specific moniker 
    - [ ] refenrece to external uid with specific moniker 
    - [ ] refenrece to another file with specific moniker
- [ ] Output xref map with moniker info.
- [ ] Static site
    - [ ] implement fallback logic on build side.
