### ISSUE TITLE
Source URL wrong with submodules

### ISSUE THREAD

**Issue by agjohnson** [dotnet/docfx#373]
The output YAML generated has an incorrect URL to the source repository when the directory path includes submodules, such as:

```
docfx.json
submodule1\
    project.json
submodule2\
    project.json
```

Even though the `project.json` files have the correct repo URL, these URLs seem to be disregarded.
### Minimal repro steps

Run docfx against https://github.com/aspnet/apidocs
### Expected result

The generated output should include YAML that points to the correct repository URL and path, such as:

``` yaml
source:
  remote:
    path: src/Microsoft.AspNet.Identity.EntityFramework/IdentityDbContext.cs
    branch: master
    repo: https://github.com/aspnet/identity
```
### Actual result

The source repository URL seems to disregard the repository URL in the respective `project.json` files, and builds up an incorrect path:

``` yaml
source:
  remote:
    path: aspnet/identity/src/Microsoft.AspNet.Identity.EntityFramework/IdentityDbContext.cs
    branch: master
    repo: https://github.com/aspnet/apidocs
```

Which is to say, GitHub will not display anything under the `aspnet/identity` path on the `aspnet/apidocs` repo. It will only serve these paths from the `github.com/aspnet/identity` URL root.
