### ISSUE TITLE
Question: How do I prevent specific protected members from getting documented?

### ISSUE THREAD

**Issue by saanandan** [dotnet/docfx#382]
### Title

I have certain methods that are declared in the following format. 

Ex 1: [DllImport("WindowsRua.dll", CallingConvention = CallingConvention.StdCall)]
        protected static extern int nativeSearchDevices(DeviceDiscoveredCallbackDel cbFunction, DiscCompleteCallbackDel cbFunction1);

Ex 2: [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        protected delegate void DevStatHandlerOnDisConnectedCallbackDel();

How do I prevent these methods from getting documented? 

My filterConfig.yml file is obviously wrong, but I do not know where. 

apiRules:
- exclude:
  DllImport
  Member: Method

**Comment by chenkennt** [comment]
Please refer to the following doc to create a correct filter:
http://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis.html#3-exclude-or-include-apis-by-containing-matched-attributes-
```yaml
  - exclude:
      hasAttribute:
        uid: System.ComponentModel.EditorBrowsableAttribute
        ctorArguments:
        - System.ComponentModel.EditorBrowsableState.Never
```
