### ISSUE TITLE
yaml parser report wrong line info

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3825]
```yaml
# bilingual build, all loc files are in one loc repo under different locale branch
# [branch mapping]
commands:
  - build --locale zh-cn
repos:
   https://github.com/ss/a:
     - files:
         docfx.yml: |
           localization:
             mapping: Branch
             bilingual: true
         docs/b.md: |
           [link to a](a.md)
         docs/a.md: abc
  https://github.com/ss/a.loc#master-sxs.zh-cn:
    - files:
        docs/a.md: |
          sxs content
          [link to b](b.md)
          [!include[include b](b.md)
  https://github.com/ss/a.loc#master.zh-cn:
    - files:
        docs/a.md: a
outputs:
  docs/a.json: |
    {"content":"<p>sxs content\n<a href=\"b\">link to b</a></p>\n<p><a href=\"a\">link to a</a></p>\n", "bilingual": true}
```

for above wrong yaml, our parser tell me that the:

```
YamlDotNet.Core.SemanticErrorException : (Line: 15, Col: 3, Idx: 377) - (Line: 15, Col: 3, Idx: 377): While parsing a block mapping, did not find expected key.

```

but the real reason gave from yaml lint is:

```
(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
```

**Comment by yufeih** [comment]
The root cause is you have 2 properties with different indention. Both line info is correct and incorrect. It really depend on the implementation of the parser. For now we pipe whatever the output from yaml.net

```yaml
commands:
  - build --locale zh-cn
repos:
   https://github.com/ss/a:      <-------- 3 indention
  https://github.com/ss/a.loc#master-sxs.zh-cn:     <----- 2 indention
```
