### ISSUE TITLE
DocFX V3 DocFX.yml

### ISSUE THREAD

**Issue by JulienM28** [dotnet/docfx#3958]
I use DocFX V3 last build, an d I am in trouble with docfx.yml.

I tried to put docfx.json properties to docfx.yml but it doesn't work.

I get this error message:
unknown-field docfx.yml(0,0): Could not find member 'metadata' on object of type 'Config'.

I tried this for yml:

````
metadata:
    src:
    - files: "**.csproj"
    exclude: "**/node_modules/**"
 template: 
  - default
````
I found nothing in V3 docs to help me.

Thanks.
