### ISSUE TITLE
Directory links in TOC don't select/expand like direct links do.

### ISSUE THREAD

**Issue by bryancostanich** [dotnet/docfx#3968]
**DocFX Version Used**: 2.40.7

**Template used**: Defaault

If you have a TOC link to a file like the following link to `Meadow.Foundation/Peripherals/index.md":

```
- name: Meadow.Foundation
  href: Meadow.Foundation/index.md
  items:
    - name: Peripherals
      href: Meadow.Foundation/Peripherals/index.md
```

Then when you click on it, the TOC item is selected and expanded as appropriate:

<img width="720" alt="screen shot 2019-01-24 at 4 36 32 pm" src="https://user-images.githubusercontent.com/947633/51717589-3a2db280-1ff6-11e9-90f6-a71a19ad4c6e.png">

However, if you link just to the directory, as in the following:

```
- name: Meadow.Foundation
  href: Meadow.Foundation/index.md
  items:
    - name: Peripherals
      href: Meadow.Foundation/Peripherals
```

Then it's neither selected, or expanded in the TOC, even though the content is rendered:

<img width="608" alt="screen shot 2019-01-24 at 4 34 40 pm" src="https://user-images.githubusercontent.com/947633/51717522-05b9f680-1ff6-11e9-8c9d-b470eb9e946a.png">

What's worse, is that if link to a directory at a root item as in the following:

```
- name: Meadow Basics
  href: Meadow_Basics
```

It doesn't even render a link!

<img width="527" alt="screen shot 2019-01-24 at 4 37 47 pm" src="https://user-images.githubusercontent.com/947633/51717633-72cd8c00-1ff6-11e9-9afa-45d628a85a05.png">

**Comment by superyyrrzz** [comment]
In TOC, when a node references a folder, DocFX will try finding the TOC under that folder and expand it. You can refer to this document for more details: https://dotnet.github.io/docfx/tutorial/intro_toc.html#link-to-a-folder

I still cannot figure out whether there is some bug as I cannot see your folder structure for now. You can provide more details if you find the behavior is not same as documented.

**Comment by perlun** [comment]
For reference, I am seeing similar semantics as you noted @bryancostanich (with DocFX 2.57.2). Referring to a folder with an `index.md` file in it works, but the TOC is not expanded. Putting a reference in the TOC to `folder/index.html` works, but has the disadvantage of exposing the `index.html` part in the user-visible URL. :grimacing: 

My `toc.yml` looks like this. This is in a subfolder btw, but I'm not sure if it matters.

```yaml
- name: Perlang
  href: index.md

- name: History
  href: history/
  homepage: history/

- name: Learn
  items:
    - name: Quickstart
      href: learn/quickstart/index.html # Change this to learn/quickstart and the bug is exhibited

    - name: The Perlang Language
      href: learn/the-language/index.html # Likewise, remove /index.html at the end to see the bug in action
```
