### ISSUE TITLE
Dependency missing for inclusion/link chain

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#4039]
`a.md` includes `b.md`, and then `b.md` includes `c.md`
```yml
inputs:
  docfx.yml:
  docs/a.md: a [!INCLUDE[](b.md)]
  docs/b.md: b [!INCLUDE[](c.md)]
  docs/c.md: c
```

In the output `.dependencymap.json`, dependency from `a.md` to `c.md` is missing
```json
{
  "dependencies": {
    "docs/b.md": [
      {
        "source": "docs/c.md",
        "type": "inclusion"
      }
    ],
    "docs/a.md": [
      {
        "source": "docs/b.md",
        "type": "inclusion"
      }
    ]
  }
}
```
The same problem with link chain also exists.
