### ISSUE TITLE
Publish Azure DevOps CI build `target` output folder as artifact

### ISSUE THREAD

**Issue by icnocop** [dotnet/docfx#4320]
**Expected Behavior**:

I expected to be able to download the contents of `.\target\Release\docfx` from Azure DevOps CI builds from https://docfx.visualstudio.com/docfx/_build.

For example, I would like to download and use a pre-release version without having to pull and build the code myself.

**Actual Behavior**:

I cannot download the build artifacts.

If `azure-pipelines.yml` was checked in, I can update and test it with the additional task, something like:
```
    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        pathtoPublish: 'target\Release\docfx'
        artifactName: target
```

Thank you.
