### ISSUE TITLE
Flawed TOC with multiple nested groups

### ISSUE THREAD

**Issue by ollie-nye** [dotnet/docfx#4378]
**Operation System**: `MacOS`

**DocFX Version Used**: 2.41.0 from `nuget install docfx.console -Version 2.41

**Template used**: `default`

**Steps to Reproduce**:

1. Create a blank default project

2a. Update articles/toc.yml with the following content:

```
- name: Introduction
  href: intro.md
- name: Articles
  items:
  - name: Nested 1
    items:
    - name: Item 1
      href: somelink
    - name: Item 2
      href: somelink
  - name: Nested 2
    items:
    - name: Item 1
      href: somelink
    - name: Item 2
      href: somelink

```

OR

2b. Update articles/toc.md with the following content:

```
#[Introduction](intro.md)
#[Articles](somelink)
##[Nested 1](somelink)
###[Item 1](somelink)
###[Item 2](somelink)
##[Nested 1](somelink)
###[Item 1](somelink)
###[Item 2](somelink)
```

3. Start the site

**Expected Behavior**: In all breakpoints, the TOC will be readable and predictably organised

**Actual Behavior**: In small breakpoints, the TOC has a flawed rendering of nested collections.
Mobile view, both expanded 
![Mobile view, both expanded](https://user-images.githubusercontent.com/26125311/56211949-eceb3b00-6050-11e9-8063-d3266beaddd5.png)
Mobile view, one expanded
![Mobile view, one expanded](https://user-images.githubusercontent.com/26125311/56211952-eceb3b00-6050-11e9-838a-74a49facac34.png)
Desktop view, both expanded (expected behaviour)
![Desktop view, both expanded (expected behaviour)](https://user-images.githubusercontent.com/26125311/56211951-eceb3b00-6050-11e9-943e-8bfff37c9412.png)
