### ISSUE TITLE
Prepare monikerDefinition file for versioning repository build

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#4489]
Three options:
1. Call OP Build rest API `GET /v2/monikertrees/allfamiliesproductsmonikers`:
    - There will be two new configs in the global config, the definition file will be downloaded in the restore step:
    ```
    monikerDefinition: https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers
    http:
        https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers:
            headers:
                X-OP-BuildUserToken: xxxx-xxxxx
    ```
    1. By running original `docsv3.ps1`, the token is already ready in the global metadata now, we can use it directly.
    2. By running the docsBuild.exe, The token can be saved in a key vault, and restore the token with the key vault connect string passed from environment variables.

2. Call DHS API
    To call DHS API, we need the `BuildServiceAADClientId` and `BuildServiceAADClientSecret` to use the `BuildServiceAADClient`, which is stored in a key vault, so we still need a key vault connecting string to restore those tokens.
    1. By running original `docsv3.ps1`, the connecting string can be passed by the global metadata.
    2. By running the docsBuild.exe,  the connecting string can be passed from environment variables.

3. Call docs API
    There is no auth required for those APIs, but currently, there are just API to get moniker by moniker name.
