### ISSUE TITLE
Remarks section only contents Description 

### ISSUE THREAD

**Issue by SFC-Sarge** [dotnet/docfx#5492]
I have a XML Comments that have custom fields in a table under the remarks section, that Sandcastle and GhostDoc does not have issues with but using DocFx it removes all of the table cells but description.  
How do I get DocFx to include these fields?
See XML comment and DocFx produced yml below:
```
    /// <summary>
    ///    Class ProvisionServers
    /// </summary>
    /// <remarks>
    ///  	<para><b>History:</b></para>
    ///  	<list type="table">
    ///  		<listheader>
    ///  			<devName>Developer</devName>
    ///  			<devDate>Date</devDate>
    ///  			<devTime>Time</devTime>
    ///  			<devCompany>Developer Company</devCompany>
    ///  			<devPhone>Developer Phone</devPhone>
    ///  			<devEmail>Developer Email</devEmail>
    ///  			<devMachine>Developer On</devMachine>
    ///  			<description>Description</description>
    ///  		</listheader>
    ///  		<item>
    ///  			**<devName>Danny McNaught</devName>
    ///  			<devDate>Thursday, January 16, 2020</devDate>
    ///  			<devTime>5:34 PM</devTime>
    ///  			<devCompany>My Company</devCompany>
    ///  			<devPhone>1-###-###-###</devPhone>
    ///  				<devEmail>
    /// 		<a href="mailto:danny.mcnaught@xxx.com">mailto:danny.mcnaught@xxx.com</a>
    /// 		<para><a href="mailto:danny.c.mcnaught@xxx.gov">mailto:danny.c.mcnaught@xxx.gov</a></para>
    /// 		<para><a href="mailto:sfcsarge@xxx.com">mailto:sfcsarge@xxx.com</a></para>
    /// 	</devEmail>
    ///  			<devMachine>1234567</devMachine>**
    ///  			<description>Created XML Comment</description>
    ///  		</item>
    ///  	</list>
    /// </remarks>
    public class ProvisionServers : IEquatable<ProvisionServers>, IComparable
```
The yml file shows that the fields and values are removed.
```
  source:
    remote:
      path: D:/OfficeWorkspaces/XXX/RssImageX64Processor-NetCore31/RssImageX64Processor-NetCore31/ProvisionServers.cs
    id: ProvisionServers
    path: ProvisionServers.cs
    startLine: 53
  assemblies:
  - RssImageX64Processor-NetCore
  namespace: RssImageProcessorX64
  summary: "\nClass ProvisionServers\n"
  remarks: "\n<p><strong>History:</strong></p>\n<table><thead><tr><th></th><th>Description</th></tr></thead><tbody><tr><td></td><td>Created XML Comment</td></tr></tbody></table>\n"
  example: []
  syntax:
    content: 'public class ProvisionServers : IEquatable<ProvisionServers>, IComparable'
```
