### ISSUE TITLE
Being able to scroll through "in this article" for larger/partial classes

### ISSUE THREAD

**Issue by Reddevildragg** [dotnet/docfx#5671]
**Operation System**: windows

**DocFX Version Used**: 2.51

**Template used**: default

**Steps to Reproduce**:

1. Create a class with a large number of methods (in my case was an extension class)
2. Generate the class with Docfx

**Expected Behavior**:
"In this Article" section behaviour to scroll up to be able to cycle though the methods quickly from this panel.

**Actual Behavior**: Only shows the number of entries it can fit in before it runs out of space.
![Screenshot_1](https://user-images.githubusercontent.com/19800074/77568307-552cd880-6ec0-11ea-831b-e95c839ab5fc.png)

This is more of a question of is there a way to do this/a request if there is not than a issue.

**Comment by WonyoungChoi** [comment]
In my case, I edited some CSS properties as follows:
```css
.affix {
  height: auto;
}

.sideaffix {
  width: 250px;
  overflow-x: hidden;
  overflow-y: auto;
}

.affix > ul.level1 {
  overflow: inherit;
}
```

I tested in 2.56.1.

**Comment by glopesdev** [comment]
@WonyoungChoi thanks a lot for this workaround, it works beautfifully! As a further improvement in my case, I found that I was able to avoid specifying the size of the `sideaffix` if I let the text wrap around (which has the further advantage that you can actually read the complete method signatures).

```css
.affix {
  height: auto;
}
  
.sideaffix {
  overflow-x: hidden;
  overflow-y: auto;
}

.affix > ul.level1 {
  overflow: inherit;
}

.affix ul > li.active > ul,
.affix ul > li.active > a:before,
.affix ul > li > a:hover:before {
  display: block;
  white-space: inherit;
}
```
