### ISSUE TITLE
Linking to another TOC file not working

### ISSUE THREAD

**Issue by reinaldoarrosi** [dotnet/docfx#635]
I'm using docfx version 2.3.1 and trying to combine multiple TOC files into a single output toc.html by using tocHref, but given the following folder/files structure:
```yml
-docs
--index.md
--toc.yml
---api
----index.md
----api1.md
----toc.yml
```

docs/toc.yml file:
```yml
- name: Intro
  href: index.md
- name: APIs
  tocHref: api/toc.yml
  topicHref: api/index.md
```

docs/api/toc.yml file:
```yml
- name: API 1
  href: api1.md
```

and given this custom TOC renderer (toc.html.liquid):
```html
{% for i in items %}
    - {{i.name}}
    {% for i2 in i.items %}
        -- {{i2.name}}
    {% endfor %}
{% endfor %}
```

I expected the output toc.html file to be (since I'm referencing docs/api/toc.yml from /docs/toc.yml):
```html
- Intro
- APIs
-- API 1
```

But instead the output toc.html is
```html
- Intro
- APIs
```

It appears that docs/api/toc.yml is not being "combined" with docs/toc.yml even though I user tocHref to reference docs/api/toc.yml.

**Comment by superyyrrzz** [comment]
@reinaldoarrosi The `tocHref` reserves in output model, which is somehow like "pass by reference". If you want to combine these TOCs like "pass by value", you should utilize `href` like:
```yml
- name: Intro
  href: index.md
- name: APIs
  href: api/toc.yml
  topicHref: api/index.md
```

Perhaps it's a bit confusing... See: http://dotnet.github.io/docfx/tutorial/intro_toc.html#link-to-another-toc-file
