### ISSUE TITLE
[Question] Highlight the landing topic in the ToC

### ISSUE THREAD

**Issue by guardrex** [dotnet/docfx#6573]
**Operating System**, **DocFX Version Used**, **Template used**: Unknown (whatever the official docs build system is currently using)

For our sidebar ToC ([ASP.NET Core official docs](https://docs.microsoft.com/aspnet/core/introduction-to-aspnet-core)), I have a node of links whose purpose is to act as an index to content in our topics. These topics have links elsewhere in the ToC (elsewhere in the `toc.yml` file). I don't want these index node entries to be highlighted when they're selected. I want the landing page to be highlighted.

Example: In the following screenshot of our sidebar ToC, I've selected the "App" component in the *Built-in components* node. The *Templates* topic loads, **_but the Templates topic in the ToC sidebar isn't highlighted ... the "App" entry (what was clicked) is highlighted_**.

Is there a way to set up the `toc.yml` for this scenario so that the *Templates* topic receives the highlight after it loads due to the reader selecting the "App" entry?

<img width="693" alt="Capture" src="https://user-images.githubusercontent.com/1622880/93604156-9fcc7080-f98a-11ea-9759-5f43537b4cd9.PNG">

... based on `toc.yml` entries of ...

```yml
- name: Templates
  uid: blazor/templates

...

- name: Components
  items:
    
    ...

    - name: Built-in components
      items:
        - name: App
          href: blazor/templates.md#blazor-project-structure

        ...
```

btw --- If there is a way to set this up in the `toc.yml` file, the docs at https://dotnet.github.io/docfx/tutorial/intro_toc.html don't explain how to do it.

If there is no way today to do this, would you consider this issue a feature request?

cc: @scottaddie
