### ISSUE TITLE
DocFx fails to generate api references in a .Net5 environment

### ISSUE THREAD

**Issue by MarkStega** [dotnet/docfx#6742]
**Operating System**: Windows (On Github Actions)

**DocFX Version Used**: 2.56.1.0

**Template used**: n/a

**Steps to Reproduce**:
We  added dual sdk (netstandard2.1;net5.0) support to a razor class library that is used in api references in our docfx project. After doing so, the default build environment on github actions. The initial run failed with
```
[20-11-02 09:07:43.227]Warning:[MetadataCommand.ExtractMetadata](D:/a/Material.Blazor/Material.Blazor/Material.Blazor/Material.Blazor.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\a\Material.Blazor\Material.Blazor\Material.Blazor\Material.Blazor.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```
We then added this action before the docfx build:
```
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Expected Behavior**:

We expect the docfx generation to work

**Actual Behavior**:

DocFx fails with
```
[20-11-06 05:39:28.280]Info:[MetadataCommand.ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin as inner compiler.
[20-11-06 05:39:28.943]Info:[MetadataCommand.ExtractMetadata]Loading projects...
[20-11-06 05:39:34.557]Warning:[MetadataCommand.ExtractMetadata](D:/a/Material.Blazor/Material.Blazor/Material.Blazor/Material.Blazor.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'D:\a\Material.Blazor\Material.Blazor\Material.Blazor\Material.Blazor.csproj' with message: The SDK 'Microsoft.NET.Sdk.Razor' specified could not be found.  D:\a\Material.Blazor\Material.Blazor\Material.Blazor\Material.Blazor.csproj
[20-11-06 05:39:34.773]Warning:[MetadataCommand.ExtractMetadata]Project 'D:\a\Material.Blazor\Material.Blazor\Material.Blazor\Material.Blazor.csproj' does not contain any documents.
```

Our only workaround is to remove the dual sdk and run docfx in the default environment (which is presumably .Net core 3.x)
