### ISSUE TITLE
Question: Using other types then "Namespace", "Class", "Interface", ...

### ISSUE THREAD

**Issue by DerAlpman** [dotnet/docfx#6743]
Hi,

I'm trying to use docfx for a programming language called Magik. I'm pretty sure that I can write a Metadata Tool for it that generates the YML files.

But for the type of an item I want to use terms like "Package", "Product" or "Module". The Metadata Specification implies that we are free in chosing types but when I create a toc.yml with this content
```

### YamlMime:ManagedReference
items:
- uid: rku_product
  id: rku_product
...
  type: Product
...
```

I get this error when running docfx.exe:

`[20-11-07 02:49:33.274]Error:[BuildCommand.BuildCore.Build Document.Load.ManagedReferenceDocumentProcessor](api_sw/rku_product.yml)Unable to load file 'api_sw/rku_product.yml' via processor 'ManagedReferenceDocumentProcessor': (Line: 10, Col: 9, Idx: 211) - (Line: 10, Col: 16, Idx: 218): Exception during deserialization`

Is there a way how I can add the types I want?
