### ISSUE TITLE
How to target syntax.parameters[X].description in overwrite file?

### ISSUE THREAD

**Issue by SMTStuck** [dotnet/docfx#6768]
Consider the abridged yml file:

```
- uid: DocFX_Test.Class1.MyMethod(System.Int32,System.Int32)
  syntax:
    content: int MyMethod(int a, int b)
    parameters:
    - id: a
      type: System.Int32
      description: This is a.
    - id: b
      type: System.Int32
      description: This is b.
    return:
      type: System.Int32
      description: Returns the sum.
```

How should the yml section of an overwrite file target the description of one of the parameters? The documentation of the website gives no complex example.

```
---
uid: DocFX_Test.Class1.MyMethod(System.Int32,System.Int32)
syntax.parameters.id[a].description: *content
---
Sample doc.
```
