### ISSUE TITLE
filterConfig not filtering methods with attribute

### ISSUE THREAD

**Issue by jalley3** [dotnet/docfx#7064]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

windows

**DocFX Version Used**: 2.56.6

**Steps to Reproduce**:

1. Filter config file:
```
apiRules:
- exclude:
    hasAttribute:
        uid: System.ComponentModel.EditorBrowsableAttribute
        ctorArguments:
        - System.ComponentModel.EditorBrowsableState.Advanced
```
2.  Attribute over code:
`[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]`

3. Metadata section of docfx.json

```
"metadata": [
    {
      "src": [
        {
          "files": [
            "src/**/**.dll"
          ],
          "exclude": [
            "**/obj/**",
            "_site/**"
          ]
        }
      ],
      "dest": "api-reference",
      "filter": "filterConfig.yml"
    }
],
```

**Expected Behavior**:
The methods that are decorated with that attribute be filtered out from a class's methods collection

**Actual Behavior**:
The internal methods decorated by the attribute described above are still present on the class' methods collections
