### ISSUE TITLE
Support multiple versions and languages of documentation

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#7070]
Is there guidance or documentation somewhere how I can support API and conceptual documentation for multiple versions of the same library? I am looking for a behaviour that is similar to docs.microsoft.com where you can select the the version of .NET for an API or conceptual article.

Also docs.microsoft.com has multi-language support (e.g. docs.microsoft.com/de-de/). How could I use docfx to add a similar  support for multiple languages?

**Comment by R0Wi** [comment]
Would also be interested in this :+1:

**Comment by dotMorten** [comment]
I wish there was better support for this too.
I at least figured out how to make an "Applies to" table with target frameworks and versions. See bottom of this page for an example:
https://dotmorten.github.io/NmeaParser/api/netfx/NmeaParser.NmeaDevice.html

All of this is on github for you to see how I did it:
https://github.com/dotMorten/NmeaParser/tree/main/docs
Main trick is I save the .manifest files for each version and target framework (this is the list of available APIs), then run the little tool in the `AppliesToGenerator` to generate a list of APIs that are supported.

It basically generates a big file like this using the [`appliesToList.json` file](https://github.com/dotMorten/NmeaParser/blob/main/docs/appliesToList.json):
```yml
---
uid: NmeaParser.BufferedStreamDevice
appliesTo:
  - platform: .NET Standard 1.4
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: .NET Framework
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: .NET Core
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: Xamarin.Android
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: Xamarin.iOS
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: UWP
    versions: GitHub, v2.0, v2.1, v2.2
---
---
uid: NmeaParser.BufferedStreamDevice.#ctor
appliesTo:
  - platform: .NET Standard 1.4
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: .NET Framework
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: .NET Core
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: Xamarin.Android
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: Xamarin.iOS
    versions: GitHub, v2.0, v2.1, v2.2
  - platform: UWP
    versions: GitHub, v2.0, v2.1, v2.2
---
```
That file is then used as an overwrite: https://github.com/dotMorten/NmeaParser/blob/be3b7aeafaaa08110fc7d4f6cd42fd31ea89cdf4/docs/docfx.json#L118-L123

Lastly this is added to a template override here: https://github.com/dotMorten/NmeaParser/blob/main/docs/template_overrides/partials/class.tmpl.partial#L63-L78


I haven't figured out how to create a version and target framework filter of the TOC based on all of this, but at least the above is a step in the right direction.
