### ISSUE TITLE
Xref mapping not working for certain uids

### ISSUE THREAD

**Issue by eaball35** [dotnet/docfx#7426]
**Operating System**: `MacOS`

**DocFX Version Used**:  `v2.56.1`

**Template used**: `default`

**Steps to Reproduce**:

1.  Generate docfx yml for class including outside uid references
2.  Include xref map with these uid references
3.  Run `docfx build` and look at generated output

**Behavior**:
Xref mapping isn't working for various classes. There doesn't seem to be an obvious pattern why this is happening. The classes that are getting skipped seemed to get skipped throughout html generation not just in a particular section. I have tested only including one problem class and I have tried changing the order in the yml and xrefmap and still have the same issue. 

Example 'inheritance' section in yml:
**input yml**
```
inheritance:
  - "java.lang.Object"
  - "java.lang.Object.Class"
  - "com.google.protobuf.AbstractMessageLite.Builder"
  - "com.google.protobuf.AbstractMessage"
  - "com.google.protobuf.AbstractMessage.Builder"
  - "com.google.protobuf.B"
  - "com.google.protobuf.ByteString"
  - "com.google.protobuf.ByteStringy"
  - "com.google.protobuf.GeneratedMessageV3"
  - "com.google.protobuf.GeneratedMessageV3.Builder"
  - "madeup.google.Thing"
  - "madeup.Other.Thing"
  - "madeup.Th"
  - "madeup.Thing"

```
**included xrefmap**
```
### YamlMime:XRefMap
baseUrl: https://cloud.google.com/java/docs/reference/client/latest/
sorted: true
references:
- uid: com.google.protobuf.AbstractMessage
  name: AbstractMessage
  href: com.google.protobuf.AbstractMessage.html
  fullName: com.google.protobuf.AbstractMessage
  nameWithType: AbstractMessage
- uid: com.google.protobuf.AbstractMessage.Builder
  name: AbstractMessage.Builder
  href: com.google.protobuf.AbstractMessage.Builder.html
  fullName: com.google.protobuf.AbstractMessage.Builder<BuilderType>
  nameWithType: AbstractMessage.Builder<BuilderType>
.... rest of above uids included in same format sorted on uid
```

**actual generated html**
```
<div class="inheritance">
    <h2>Inheritance</h2>
    <span><span class="xref">java.lang.Object</span></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/java.lang.Object.Class.html">Object.Class</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.AbstractMessageLite.Builder.html">AbstractMessageLite.Builder&lt;MessageType,BuilderType&gt;</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.AbstractMessage.html">AbstractMessage</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.AbstractMessage.Builder.html">AbstractMessage.Builder</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.B.html">B</a></span> <span> &gt; </span>
    <span><span class="xref">com.google.protobuf.ByteString</span></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.ByteStringy.html">ByteStringy</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/com.google.protobuf.GeneratedMessageV3.html">GeneratedMessageV3</a></span> <span> &gt; </span>
    <span><span class="xref">com.google.protobuf.GeneratedMessageV3.Builder</span></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/madeup.google.Thing.html">Thing</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/madeup.google.Other.Thing.html">Other.Thing</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/madeup.Th.html">Th</a></span> <span> &gt; </span>
    <span><a class="xref" href="https://cloud.google.com/java/docs/reference/client/latest/madeup.Thing.html">Thing</a></span> <span> &gt; </span>
    <span class="xref">SpeechContext.Builder</span>
  </div>
```
**expected behavior**
`com.google.protobuf.ByteString`, `com.google.protobuf.GeneratedMessageV3.Builder`, `java.lang.Object` should have the appropriate href included.
