### ISSUE TITLE
Right-hand navigation box cut off due to 'overflow: hidden' in docfx.css 'sideaffix' class

### ISSUE THREAD

**Issue by jtalsby** [dotnet/docfx#7538]
The `.sideaffix` class in `https://dotnet.github.io/docfx/styles/docfx.css` has the property `overflow: hidden`, which cuts off the rest of the headers and prevents scrolling. This can be most clearly seen in the [Version Notes page](https://dotnet.github.io/docfx/RELEASENOTE.html?tabs=csharp).

Also, the element containing `.sideaffix` should not have an inline `style="bottom: 70px;"` attribute (`.sideaffix` has a `bottom: 10px;` property, which is overridden by the inline styling). The positioning also needs to be adjusted to be moved down a bit more, and the width should be increased to improve readability.

The original `.sideaffix` class is:

```css
.sideaffix {
    margin-top: 50px;
    font-size: 12px;
    max-height: 100%;
    overflow: hidden;
    top: 100px;
    bottom: 10px;
    position: fixed;
}
```

However, the `.sideaffix` class should really be more like:

```css
.sideaffix { 
    position: fixed;
    bottom: 60px;
    width: 200px;
    height: 425px;
    overflow-y: scroll;
    font-size: 12px;
}
```

The following could also be added below the `.sideaffix` class in `docfx.css` to update the scroll bar to have a more modern look:

```css
.sideaffix::-webkit-scrollbar {
  width: 5px;
}

.sideaffix::-webkit-scrollbar-track {
  background: #f1f1f1;
}

.sideaffix::-webkit-scrollbar-thumb {
  background: #888;
}

.sideaffix::-webkit-scrollbar-thumb:hover {
  background: #555;
}
```
