### ISSUE TITLE
filterConfig, exclude all except classes contains specific attribute

### ISSUE THREAD

**Issue by rafbart** [dotnet/docfx#7546]
**Operating System**: (`Windows`)

**DocFX Version Used**:  2.58

**Template used**: default

**Steps to Reproduce**:

1. I would like to exclude all
2. I would like to include only classes contains specific attribute

My filterConfig.yml file:

```
apiRules:
- include:
    hasAttribute:
      uid: TechTalk.SpecFlow.BindingAttribute
- exclude:
    uidRegex: ^.*$
    type: Namespace
```

**Expected Behavior**:
Only classes contains TechTalk.SpecFlow.BindingAttribute will be shown

**Actual Behavior**:
Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for api.
