### ISSUE TITLE
Exclude type or members based on an attribute

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#7814]
Is there a way to exclude public types or members based on an attribute that type or member has? If not, this would make a really nice feature! 😉

**Comment by bitbonk** [comment]
I just found it [in the docs](https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html):

```yaml
 - exclude:
      hasAttribute:
        uid: System.ComponentModel.EditorBrowsableAttribute
        ctorArguments:
        - System.ComponentModel.EditorBrowsableState.Never
```
