### ISSUE TITLE
Guidance for plugin development

### ISSUE THREAD

**Issue by mattwhitfield** [dotnet/docfx#7971]
Hello

I have written a plugin for v2 that allows TOCs to use glob matching patterns to include multiple files - so you can do stuff like this in TOC.yml
```
- name: Some specific file
  href: someSpecificFile.md
- name: All other files
  items:
  - name: Expand{Hierarchical}
    includedFrom: '**/*.md'
```

I have two questions - 

1) Is there a good process for distribution for plugins?
2) The plugin is built against the 2.59 nuget packages currently - is there any information about how to go about porting it for v3? I have tried to find information on it but I don't see any v3 preview packages on nuget.org and I couldn't find anything about plugins that was specific to v3. Apologies if my google-fu is weak.
