### ISSUE TITLE
seealso yml tag not supported in overwrite files

### ISSUE THREAD

**Issue by glopesdev** [dotnet/docfx#8171]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59.4

**Template used**: `default`

**Steps to Reproduce**:

1. Create an overwrite file for some uid (e.g. apiSpec/MyNamespace_MyClass.md)
2. Specify a YML header with a `seealso` field:
```yml
---
uid: MyNamespace.MyClass
seealso:
- linkId: MyNamespace.MyExtendedClass
---
``` 

**Expected Behavior**: The output doc page for `MyClass` should contain a "See Also" section with a link to `MyExtendedClass` documentation page.

**Actual Behavior**: The output doc page for `MyClass` contains a "See Also" section but with no links.
