### ISSUE TITLE
Is there any demo of using overwriting with docfx v3?

### ISSUE THREAD

**Issue by gggdttt** [dotnet/docfx#8215]
**Operating System**: Windows

**DocFX Version Used**: 3

**Template used**:  dynamic 365 business center

**Steps to Reproduce**:

1. Follow all the steps shown in https://dotnet.github.io/docfx/tutorial/intro_overwrite_files.html
2. Tried both _docfx.json_ and _docfx.yml_ file. All the overwriting `.md` file is put under folder `content`, with `uid` specified.
``` yml 
globalMetadata:
  titleSuffix: My Awesome Website
overwrite: content/**.md
exclude: 
- ./template/**
template: template
```
3.  The page can not show overwriting content correctly.

**Expected Behavior**: 

**Actual Behavior**:

**Comment by gggdttt** [comment]
I am not sure if the guidance is only for docfx v2? Because I tried docfx2 and it worked. But when I changed to docfx3, it fails to render.

**Comment by gggdttt** [comment]
Hi, 
sorry to reopen this issue.
Now I am following [markdown fragment](https://github.com/dotnet/docfx/blob/v3/docs/designs/markdown-fragments.md), but I don't know why it does not work completely. 
Now my file is:
|--override
    |--test.md
|--ref
    |--String.yml

The content of test.md is :
````markdown
# `System.String`
```  yaml
author: rpetrusha
ms.author: ronpet
manager: wpickett
```
## `summary`
Represents text as a sequence of UTF-16 code units.

## `remarks`
A string is a sequential collection of characters that is used to represent text.

### Instantiating a String object

## `return/description`
Markdown content
## `parameters[id="parameterName"]/description`
Markdown content
````

And my String.yml is
```yml
uid: System.String
parameters:
- id: parameterName
children:
- uid: System.String.#ctor(System.Char*)
```

After follow the guidance, I don't know why nothing happen, the content of string.html does not change.
Should I change some config in docfx.yml?

**Comment by gggdttt** [comment]
My config is:
```yml
template: ./template/
exclude: ./template/**
globalMetadata:
  titleSuffix: My Awesome Websites
```
