### ISSUE TITLE
Unable to set landing page

### ISSUE THREAD

**Issue by v-trisshores** [dotnet/docfx#8231]
**Operating System**: Windows

**DocFX Version Used**: 2.59.4

**Template used**: (`default` or `statictoc` or contain custom template)

**Steps to Reproduce**:

1) Use the following root toc (resource: DocFX [page](https://dotnet.github.io/docfx/tutorial/intro_toc.html)) to set a markdown doc in a subfolder as the home page for localhost:8080. This is part of a migration to Engineering Hub.

```
- name: Troubleshooting Guides
  href: tsgs/toc.yml
  topicHref: tsgs/aadlcm-oncall-handbook/lcm-dependency-map.md
```

2) Here's the nested /tsgs/toc.yml:

```
- name: AADLCM OnCall handbook
  items:
  - name: AAD LCW OnCall HandBook
    href: aadlcm-oncall-handbook/aad-lcw-oncall-handbook.md
  - name: LCM Dependency Map
    href: aadlcm-oncall-handbook/lcm-dependency-map.md
```

3) Run DocFX locally on the docfx.json in the root folder.

**Expected Behavior**:

Should see the Markdown article specified by the topicHref as the landing page.

**Actual Behavior**:

I get an index listing:
![image](https://user-images.githubusercontent.com/86677757/198716293-6dd1452c-e5bf-42c7-b653-ef01c497e8a2.png)
