### ISSUE TITLE
[Bug] TOC Names in PDF are written twice everytime.

### ISSUE THREAD

**Issue by Lagann311** [dotnet/docfx#8392]
**Describe the bug**
When DocFX creates a new PDF File, every name in the Table Of Contents is written twice.
Clicking the link of the first name jumps to the right section (although a few pages past to where the Heading is).
Clicking the link of the second occurence has no effect.

**To Reproduce**
1. Create a new DocFX Project with default settings.
2. Copy and paste desired source code to /src folder
3. Install and configure wkhtmltopdf
4. Add PDF section as described in DocFX docs under PDF section
`"pdf": {
    "content": [{
      "files": [ "**/*.{md,yml}" ]
    }],
    "wkhtmltopdf": {
      "additionalArguments": "--enable-local-file-access"
    },
  }`
5. Run **docfx pdf**

**Expected behavior**
TOC Names should be written only once.

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: [2.61.0]

**Additional context**
This wasn't a problem in previous versions of DocFX. I don't know since when this issue occured however.

**Comment by bruennlein** [comment]
Hi all,

it´s the same thing for me. I´ve added several TOCs to have multiple per-toppic PDFs. On the website, everything looks fine. In the PDF, I have duplicate entries.

**Config:**
```json
"pdf": {
      "content": [
        {
          "files": [ "pdf/Test_Environments/toc.yml" ],
          "dest": "DevOps/Guidelines/"          
        },
        {
          "files": [ "pdf/Test_Environments/Guacamole-manual/toc.yml" ],
          "dest": "DevOps/Guidelines/"
        },
        {
          "files": [ "pdf/Test_Environments/VPN-access/toc.yml" ],
          "dest": "DevOps/Guidelines/"
        },
        {
          "files": [ "DevOps/Guidelines/Test_Environments/**/*.{md,yml}" ]         
        }        
      ],
      "resource": [
        {
          "files": [ "DevOps/Guidelines/Test_Environments/Guacamole-manual/img/*.png"]
        },
        {
          "files": [ "DevOps/Guidelines/Test_Environments/Test-guide/img/*.png"]
        }
      ],
      "wkhtmltopdf": {
        "additionalArguments": "--enable-local-file-access --no-background --disable-javascript --disable-external-links",
        "filePath": "C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"        
      }      
    }
```

**TOC:**
```yaml
- name: Test Environments
  items:
    - name: Test Environments manual
      topicUid: test-environments-test-manual
    - name: VPN-access (CTL)
      topicUid: test-environments-guacamole-user-manual-setup-vpn-connection
    - name: Guacamole user-manual
      topicUid: test-environments-guacamole-user-manual
    - name: Start Terminal-session
      topicUid: test-environments-test-manual-start-terminal-session
    - name: CMGS-enrollment
      topicUid: test-environments-test-manual-physical-machine-enrollment
```

The result looks like **this:**

![duplicateTOC pdf](https://user-images.githubusercontent.com/14270748/221797798-1a0fbcbc-3d23-4ecc-94cf-722b6af85f04.png)

I´ve also tried to remove the "name:"-fields from the TOC, but it still duplicates the entries.
