### ISSUE TITLE
Custom xrefProperties for Conceptual Documents

### ISSUE THREAD

**Issue by softworkz** [dotnet/docfx#8401]
I have conceptual documents with headers like this:

```yml
---
uid: Fpp-Bar
title: Foo the Bar
longTitle: How can I foo the bar while the bar is fooing the foo?
---
```

Now I want to be able to use the long title for display in links, like for example: `@Foo-Bar?displayName=longTitle`  and I would also like to have longTitle in the xrefMap file.

I have seen that the document schema definitions can specifiy the properties used for xref through the `xrefProperties` property.
That makes sense so far, but what's totally unclear to me is how to get this going practically with my conceptual documents.

What's the trick?

Thanks,
sw
