### ISSUE TITLE
[Bug] Additional namespace spec.csharp/spec.vb introduced in release 2.61.0

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#8660]
**Describe the bug**

Additional details for namespace references were introduced in metadata in 2.61.0, causing some nasty rendering issues like this:

![Broken namespace documentation](https://user-images.githubusercontent.com/17011/233581992-cb71772e-a6e8-49ae-95df-a39102bf02a2.png)

With a more deeply nested namespace, the problem is even worse:

![Another example of broken namespace documentation](https://user-images.githubusercontent.com/17011/233585245-beb4fdc7-ab18-4a39-a2fc-4958f74eb217.png)

Our scenario is a particularly complicated one (not just "build metadata, build the site, publish") and we could *potentially* change our template to work around this (or remove the spec.csharp/spec.vb sections ourselves), but we'd prefer not to - at least not until we know that the change is really deliberate.

**To Reproduce**

Code:

```csharp
namespace Google.Cloud.Test;

/// <summary>Class summary</summary>
public class Library
{
}
```

docfx.json:

```json
{
  "metadata": [{
    "src": [{ "files": ["*.csproj"]}],
    "dest": "api",
  }]
}
```

(The project is just a default "dotnet new classlib" targeting .NET 6.)

Only metadata generation is required to see the change.

**Old vs new behavior**

When generating the metadata with 2.60.2 (or earlier), the references section of Google.Cloud.Test.Library.yml starts like this:

```yaml
references:
- uid: Google.Cloud.Test
  commentId: N:Google.Cloud.Test
  name: Google.Cloud.Test
  nameWithType: Google.Cloud.Test
  fullName: Google.Cloud.Test
```

As of 2.61.0, the first entry is instead:

```yaml
references:
- uid: Google.Cloud.Test
  commentId: N:Google.Cloud.Test
  name: Google.Cloud.Test
  nameWithType: Google.Cloud.Test
  fullName: Google.Cloud.Test
  spec.csharp:
  - uid: Google
    name: Google
  - name: .
  - uid: Google.Cloud
    name: Cloud
  - name: .
  - uid: Google.Cloud.Test
    name: Test
  spec.vb:
  - uid: Google
    name: Google
  - name: .
  - uid: Google.Cloud
    name: Cloud
  - name: .
  - uid: Google.Cloud.Test
    name: Test
```

It looks like without these spec.csharp and spec.vb sections, the documentation is generated correctly.

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: Change occurred between 2.60.2 and 2.61.0
