### ISSUE TITLE
[Bug] modern missing dropdown on navbar

### ISSUE THREAD

**Issue by Aragas** [dotnet/docfx#8693]
**Describe the bug**
Switching to the modern template breaks the navbar dropdowns, plus the link is broken and leads to `{BASE}/undefined` instead of the right 'section'(`{BASE}/api`, etc.)

**To Reproduce**
Add to the root toc something like this
```yaml
- name: Bannerlord Documentations
  dropdown: true
  items:
  - name: Official Documentation
    href: https://docs.modding.bannerlord.com
  - name: Community Documentation
    href: https://docs.bannerlordmodding.com
```
As you see, it works with the sidebar, but not with the navbar

**Expected behavior**
A dropdown in shown like in the default template (the screenshot is a bit modified default template before 2.60)
![image](https://user-images.githubusercontent.com/5411011/234784532-821a4e78-e71c-4544-a010-749676e6c32d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/5411011/234784039-8516a906-e761-4f31-9b75-e67bd6eeb2bb.png)

**Context (please complete the following information):**
- Browser: any
- Form factor: any
- Docfx version: 2.61.2
- Template: modern

**Additional context**
None required
