### ISSUE TITLE
[Bug] Interface inheritance causing maximum recursion limit error

### ISSUE THREAD

**Issue by soumyart** [dotnet/docfx#9236]
**Describe the bug**

Getting below error while building docs.

 ` error ApplyTemplateRendererError: Error applying template "UniversalReference.html.primary" generated from "obj/yml/input-manager/main.yml". To get the detailed view model, please run docfx with debug mode --debug. You have reached the maximum recursion limit of 256.`

**Root cause Analysis**
After some debugging in docfx source code using custom templates, figure out that the below line is causing the issue. 
https://github.com/dotnet/docfx/blob/5c145e96970aef074b4be5736c39b0f38a9f5ea4/templates/common/UniversalReference.common.js#L31

For interface extending another interface if `model.isClass` is set to true it is creating some kind of infinite loop. I'm not sure why though.

Below are the Details of the code snippet and configuration. Same is available in https://github.com/soumyart/docfx_bug_report/tree/main

```ts
export interface Common {
  name: string;
}

/**
 * @public
 */
export interface Main extends Common {
  value: string;
}

/**
 * @public
 */
export class MainImpl implements Main {
  value: string = '';
  name: string = '';
}
```

For the above typescript snippet I have generated the docs yml file using microsoft [api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) and [api-documentor](https://www.npmjs.com/package/@microsoft/api-documenter). 
Below are the generated yml files which is input to the docfx

**To Reproduce**

1. Use the below configs in a standard docfx boilerplate project
2. Run docfx from command line

**obj/yml/toc.yml**
```yml
items:
  - name: Input Manager reference
    uid: input-manager-api
    items:
      - name: input-manager
        uid: 'input-manager!'
        items:
          - name: Common
            uid: 'input-manager!Common:interface'
          - name: Main
            uid: 'input-manager!Main:interface'
          - name: MainImpl
            uid: 'input-manager!MainImpl:class'

```
**obj/yml/input-manager.yml**
```yml
### YamlMime:UniversalReference
items:
  - uid: 'input-manager!'
    summary: InputManager
    name: 'input-manager'
    fullName: 'input-manager'
    langs:
      - typeScript
    type: package
    alias:
      - input-manager
    children:
      - 'input-manager!Common:interface'
      - 'input-manager!Main:interface'
      - 'input-manager!MainImpl:class'
references:
  - uid: 'input-manager!Common:interface'
    name: Common
  - uid: 'input-manager!Main:interface'
    name: Main
  - uid: 'input-manager!MainImpl:class'
    name: MainImpl

```
**obj/yml/input-manager/common.yml**
```yml
### YamlMime:UniversalReference
items:
  - uid: 'input-manager!Common:interface'
    name: Common
    fullName: Common
    langs:
      - typeScript
    type: interface
    package: 'input-manager!'
    syntax:
      content: 'export interface Common '
    alias:
      - 'input-manager!Common'
      - 'Common:interface'
      - Common
    children:
      - 'input-manager!Common#name:member'
  - uid: 'input-manager!Common#name:member'
    name: name
    fullName: Common.name
    langs:
      - typeScript
    type: property
    syntax:
      content: 'name: string;'
      return:
        type:
          - string
    parent: 'input-manager!Common:interface'
    alias:
      - 'input-manager!Common#name'
      - 'Common#name:member'
      - 'Common#name'
      - 'name:member'
      - name
references:
  - uid: string
```
**obj/yml/input-manager/main.yml**
```yml
### YamlMime:UniversalReference
items:
  - uid: 'input-manager!Main:interface'
    name: Main
    fullName: Main
    langs:
      - typeScript
    type: interface
    extends:
      - 'input-manager!Common:interface'
    inheritance:
      - type: 'input-manager!Common:interface'
    package: 'input-manager!'
    syntax:
      content: 'export interface Main extends Common '
    inheritedMembers:
      - 'input-manager!Common#name:member'
    alias:
      - 'input-manager!Main'
      - 'Main:interface'
      - Main
    children:
      - 'input-manager!Main#value:member'
  - uid: 'input-manager!Main#value:member'
    name: value
    fullName: Main.value
    langs:
      - typeScript
    type: property
    syntax:
      content: 'value: string;'
      return:
        type:
          - string
    parent: 'input-manager!Main:interface'
    alias:
      - 'input-manager!Main#value'
      - 'Main#value:member'
      - 'Main#value'
      - 'value:member'
      - value
references:
  - uid: 'input-manager!Common:interface'
    name: Common
  - uid: string
```
**obj/yml/input-manager/mainimpl.yml**
```yml
### YamlMime:UniversalReference
items:
  - uid: 'input-manager!MainImpl:class'
    name: MainImpl
    fullName: MainImpl
    langs:
      - typeScript
    type: class
    implements:
      - 'input-manager!Main:interface'
    package: 'input-manager!'
    syntax:
      content: 'export declare class MainImpl implements Main '
    alias:
      - 'input-manager!MainImpl'
      - 'MainImpl:class'
      - MainImpl
    children:
      - 'input-manager!MainImpl#name:member'
      - 'input-manager!MainImpl#value:member'
  - uid: 'input-manager!MainImpl#name:member'
    name: name
    fullName: MainImpl.name
    langs:
      - typeScript
    type: property
    syntax:
      content: 'name: string;'
      return:
        type:
          - string
    parent: 'input-manager!MainImpl:class'
    alias:
      - 'input-manager!MainImpl#name'
      - 'MainImpl#name:member'
      - 'MainImpl#name'
      - 'name:member'
      - name
  - uid: 'input-manager!MainImpl#value:member'
    name: value
    fullName: MainImpl.value
    langs:
      - typeScript
    type: property
    syntax:
      content: 'value: string;'
      return:
        type:
          - string
    parent: 'input-manager!MainImpl:class'
    alias:
      - 'input-manager!MainImpl#value'
      - 'MainImpl#value:member'
      - 'MainImpl#value'
      - 'value:member'
      - value
references:
  - uid: 'input-manager!Main:interface'
    name: Main
  - uid: string

```

**docfx.json**
```json
{
  "build": {
    "template": [
      "default",
      "modern"
    ],
    "content": [
      {
        "files": ["**/**/*.yml", "**/*.md"],
        "src": "obj/yml",
        "dest": "api"
      }
    ],
    "resource": [
      {
        "files": ["images/**"]
      }
    ],
    "exportRawModel": true,
    "rawModelOutputFolder": "obj/raw",
    "exportViewModel": true,
    "viewModelOutputFolder": "obj/view",
    "globalMetadata": {
      "_appTitle": "API Reference",
      "_enableNewTab": true
    },
    "output": "_site"
  }
}
```

**Expected behavior**
Documentation should be build without any errors.

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.70.4+c3de0ca32a12f6126194f26b22f56657e9664c6c

**Additional context**
Created below sample repo to replicate the issue

https://github.com/soumyart/docfx_bug_report/tree/main
