### ISSUE TITLE
[Feature Request] Images for light and dark theme

### ISSUE THREAD

**Issue by okvalsralos** [dotnet/docfx#9386]
**Describe the solution you'd like**
docfx has a switcher in the header that lets readers choose between the light and the dark theme. If applicable authors should provide both the light and the dark version of every screenshot used in the documentation.

**Additional context**
Add the `_dark.png`  suffix to the name of the dark image version. This image will be then used when the user switches to the dark theme.

For example dafault images can be used in both the light and dark theme.

When , save images as `example.png`   and `example_dark.png` 
(image used when user switches to the dark theme).

**Comment by BarkenBark** [comment]
+1

**Comment by CaseyHofland** [comment]
+1

**Comment by bitbonk** [comment]
Until this feature is implemented, do you known of any trick or workaround how to provide different images (and some icons) based on the theme?

**Comment by zhaparoff** [comment]
Or at least set light theme as default and disable theme switcher without deep diving into custom template creation...

**Comment by psdehr** [comment]
It depends on the logo, but it's possible to create a transparent background logo which will work in light and dark themes.

**Comment by bouda19** [comment]
@bitbonk 

You can achieve that by adding a custom template and a `main.css` file with the following content :

```css
#logo {
    margin-right: 10px;
}

[data-bs-theme=dark] #logo {
    content:url("../images/dark-logo.png");
}

[data-bs-theme=light] #logo {
    content:url("../images/light-logo.png");
}
```

I have created a [sample repo](https://github.com/bouda19/docfx-image-light-dark-modern-template-sample) and a sample [demo site](https://bouda19.github.io/docfx-image-light-dark-modern-template-sample/) if needed.
