### ISSUE TITLE
API Filtering Yml Cannot Include Specific Namespace

### ISSUE THREAD

**Issue by groogiam** [dotnet/docfx#9404]
**Describe the bug**
The api filtering yml mechanism does not allow keeping a specific sub namespace as per https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#filter-by-uid.

**To Reproduce**

The following api rules yml does filters out all items in the `MyProject.Server` namespace.

```yml
apiRules:
- include:
    uidRegex: ^MyProject\.Server\.Config
- exclude:
    uidRegex: ^MyProject\.Server
```

**Expected behavior**
Based on the documentation this should generate docs for only MyProject.Server.Config

It seems like the excludes are taking precedence over the includes.

**Context (please complete the following information):**
- OS: Windows 10 Pro
- Docfx version: 2.73.1+1d7b96c23465e14eafbcb0dd765029a87b5312d4

**Comment by groogiam** [comment]
Is there any update on this?

**Comment by filzrev** [comment]
It seems to be resolved by adding type: Type restriction to the exclude rule.

```
apiRules:
- include:
    uidRegex: ^MyProject\.Server\.Config
- exclude:
    uidRegex: ^MyProject\.Server
    type: Type
```

**Background**
Filter rules are evaluated by  [`ConfigFilterRule::CanVisitCore` method](https://github.com/dotnet/docfx/blob/e2f78e99c079d32c9ec0e8d764dd027e7821b196/src/Docfx.Dotnet/Filters/ConfigFilterRule.cs#L28-L39)
Based on the order defined at `filterConfig.yml'.

But It also checking [`symbol.ContainingSymbol` recursively](https://github.com/dotnet/docfx/blob/e2f78e99c079d32c9ec0e8d764dd027e7821b196/src/Docfx.Dotnet/SymbolFilter.cs#L70-L77)

If `MyProject\.Server` is excluded by filter config without type restriction.
Then `IncludeAttributeDefault` method return `false` for symbol that expected to be included.

I thought it need to fix [documentation](https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#filter-by-uid)
or need to change type check logics when `type` is not specified.
