### ISSUE TITLE
No top navbar or TOC sidebar in generated home

### ISSUE THREAD

**Issue by Myrmex** [dotnet/docfx#9567]
I am using docfx to create the documentation of a Visual Studio 2022 solution. My root folder (where the solution file is found) contains:

- `docfx.json`;
- `index.md`, for the homepage;
- `toc.yml`;
- a `docs` folder with `toc.yml` and various Markdown files with conceptual documentation. All the images referenced by these Markdown files are under `docs/img`.
- an `api` folder whose content is generated by docfx from `csproj` files.

Here is my `docfx.json`:

- `src` is the current folder, which contains the `sln` file and a subfolder for each project.
- I exclude test projects from the documentation.
- `dest` is `api`, which initially is empty.
- content files are all the Markdown and YML files from docs, and all the YML files from api. The default configuration also contains `api/index.md` which anyway is not there nor does seem to be used. Anyway, if I add this it makes no difference.

```json
{
  "metadata": [
    {
      "src": [
        {
          "src": ".",
          "files": ["**/*.csproj"],
          "exclude": ["**/*.Test.csproj", "**/bin/**", "**/obj/**"]
        }
      ],
      "dest": "api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "docs/**/*.md",
          "docs/**/*.yml",
          "api/**.yml",
          "api/index.md"
        ],
        "exclude": ["_site/**", "docs/old/**"]
      }
    ],
    "resource": [
      {
        "files": ["docs/img/**"]
      }
    ],
    "output": "_site",
    "template": ["default", "modern"],
    "globalMetadata": {
      "_appName": "chiron-doc",
      "_appTitle": "chiron-doc",
      "_enableSearch": true,
      "pdf": true
    }
  }
}
```

When running docfx, all the files seem to be generated as expected; the `api` folder is full of HTML files from project namespaces, and I have all the HTML files for conceptual documentation. Yet, when I serve with `docfx --serve` and open the homepage at <localhost:8080>, I get the homepage without the top menubar and the TOC sidebar. If I manually open any of the HTML files from `api` or `docs` I can see that they have a working TOC on the sidebar, and images work too; but none has the top menubar. The home instead has my home's content, but no links at all.

The root menu shold be generated from the root `toc.yml` file, whose content is:

```yml
- name: Docs
  href: docs/
- name: API
  href: api/
```

The TOC sidebar should be generated from `docs/toc.yml`, whose content is:

```yml
- name: Introduction
  href: introduction.md
- name: Getting Started
  href: start.md
- name: Overview
  href: overview.md
- name: Input
  href: input-format.md
- name: Pipeline
  href: pipeline.md
- name: Factories
  href: factories.md
- name: Lab
  href: lab.md
- name: Storage
  href: storage.md
- name: Command Line Interface
  href: cli.md
```

I have tried to use the `statictoc` template instead of the default and modern templates, but nothing changes. I can be sure that all the builtin templates required are present by running `docfx template list`. My docfx version (from `docfx --version`) is the latest available at the time of writing, `2.74.1+80bc27e44183b48c74d24728655fa0729ae95689`.

So, how am I supposed to configure docfx for a typical Visual Studio solution, having a `sln` file and as many subfolders as projects, each with its own `csproj` file, plus a `docs` subfolder with Markdown files for conceptual documentation?
