### ISSUE TITLE
[Bug] How to use the latest docfx with unity / Generate documentation using only source files

### ISSUE THREAD

**Issue by Ccccraz** [dotnet/docfx#9675]
Hi I use docfx on window and try to use it to generate documentation for my Unity project.

- Platform: win11 23H2 22631.3007
- .Net: v8.0.101
- Unity: v2022.3
- docfx: v2.75.2

In unity, the concept of project is weakened, and I want to be able to generate documentation from source files, all this was fine in `v2.61.0` version of docfx, I could generate documentation using only source files. But in the latest version `v2.75.2` I can't generate documentation just from source files. (Generating documentation from csproj is normal in the `v2.75.2`)

![image](https://github.com/dotnet/docfx/assets/30764038/be5bc0bd-8630-44dc-85b9-ccc41d1922aa)
This is the main error message. It looks like it's mainly caused by not being able to find the UnityEngine namespace.

So I made the following attempt:
1. add filterConfig.yml --> failed
```yaml
{
  "metadata": {
    "src": [{
      "files": ["**/*.cs"],
      "src": "../Assets"
    }],
    "dest": "api",
    "filter": "filterConfig.yml"
  }
}
```
```yaml
apiRules:
- include:
    uidRegex: ^Mynamespace
    type: Namespace
- exclude:
    uidRegex: ^UnityEngine
    type: Namespace
```
2. add UnityEngine.dll as reference --> still failed
```yaml
{
  "metadata": {
    "src": [{
      "files": ["**/*.cs"],
      "src": "../Assets"
    }],
    "dest": "api",
    "references": [
      "path-to-UnityEngine.dll"
    ]
  },
}
```
The output error log is unchanged from before.

Did I miss something? Is this generation method not recommended or has it been removed in the current version?
