### ISSUE TITLE
[Bug] Print styles being ignored

### ISSUE THREAD

**Issue by cjlotz** [dotnet/docfx#9730]
**Describe the bug**
Custom styles created for printing does not seem to get applied.  I'm trying to change the background-color of the code blocks as the background color used for web output does not match the printed output.  I've added the following CSS to my custom `main.css` file

```css
@media print {
    section[role="tabpanel"] {
        display: block !important;
    }

    .hljs {
        background-color: aliceblue;
    }
}
```

The section[role] gets applied, but the background-color overide does not get applied.  I've verified that the .hljs override does work when applied to the whole site and not only to print media selector.
