### ISSUE TITLE
[Bug] "Exception: The server disconnected unexpectedly." when running in Azure Devops

### ISSUE THREAD

**Issue by BarkenBark** [dotnet/docfx#9855]
**Describe the bug**
When running `docfx` to build my project documentation in Azure Devops, I get `Exception: The server disconnected unexpectedly.` followed by a stack trace (see log below). The exact command run is `docfx docs/docfx.json --output 'D:\a\1\a\docs' --warningsAsErrors`.

The _docfx.json_ is the same as it has been previously successful runs. Will post a redacted version if needed.

The crash does not occur when running the same command locally on my machine, and I have not been able to reproduce is locally.

<details>
<summary>Log</summary>

```
+ docfx docs/docfx.json --output 'D:\a\1\a\docs' --warningsAsErrors
Loading project <REDACTED>
  Determining projects to restore...
  All projects are up-to-date for restore.
Exception: The server disconnected unexpectedly.
  at async Task<object> InvokeCoreAsync(int targetObject, string methodName,    
     List<object> parameters, Type expectedReturnType, CancellationToken        
     cancellationToken)                                                         
  at async Task<T> InvokeAsync<T>(int targetObject, string methodName,          
     List<object> parameters, CancellationToken cancellationToken)              
  at async Task<RemoteProjectFile> LoadProjectFileAsync(string projectFilePath, 
     string languageName, CancellationToken cancellationToken)                  
  at async Task<TResult> DoOperationAndReportProgressAsync<TResult>(            
     ProjectLoadOperation operation, string projectPath, string targetFramework,
     Func<Task<TResult>> doFunc)                                                
  at async Task<ImmutableArray<ProjectFileInfo>> LoadProjectFileInfosAsync(     
     CommandExecutor.cs:144                                                     
  at async Task<int> Execute(IConfiguration configuration, IEnumerable<string>  
     args) in CommandExecutor.cs:83                                             
  at async Task<int> RunAsync(IEnumerable<string> args) in CommandApp.cs:84  
```
</details>

**To Reproduce**
1. Run `docfx` in Azure Devops  on VM Image `windows-2022` (Version20240403.1.0)

**Expected behavior**
The docs should build succesfully.

**Context (please complete the following information):**
- OS: Azure Devops VM Image: `windows-2022` (Version 20240403.1.0)
- Docfx version: 2.76

**Additional context**
- **UPDATE:** Downgrading to version 2.75.3 solves the issue for me.

**Comment by filzrev** [comment]
> Exception: The server disconnected unexpectedly.

It seems to be thrown by following lines when calling `MSBuildWorkspace::LoadProjectFileAsync`.
https://github.com/dotnet/roslyn/blob/b67df4c5e39ac1a104b2e573542211d4d6b1cd1d/src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs#L87-L89

docfx 2.76.0 using roslyn 4.9.2 packages. and out-of-process that are introduced in this version causing problems.
It might be resolved when next roslyn packages (v4.9.10) are released.
Related issue: https://github.com/dotnet/roslyn/issues/72558

**Comment by thejonan** [comment]
Same problem here on a local project, after update from `2.75.3` to `2.76.0`.

Here's the output:
```
Loading project /Users/jonan/LABS/COZYROC/CozyFlow/src/Core/CozyFlowCore.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
Exception: The server disconnected unexpectedly.
  at async Task<object> InvokeCoreAsync(int targetObject, string methodName, List<object> parameters, Type
     expectedReturnType, CancellationToken cancellationToken)
  at async Task<T> InvokeAsync<T>(int targetObject, string methodName, List<object> parameters, CancellationToken
     cancellationToken)
  at async Task<RemoteProjectFile> LoadProjectFileAsync(string projectFilePath, string languageName, CancellationToken
     cancellationToken)
  at async Task<TResult> DoOperationAndReportProgressAsync<TResult>(ProjectLoadOperation operation, string projectPath,
     string targetFramework, Func<Task<TResult>> doFunc)
  at async Task<ImmutableArray<ProjectFileInfo>> LoadProjectFileInfosAsync(string projectPath, DiagnosticReportingOptions
     reportingOptions, CancellationToken cancellationToken)
  at async Task<ImmutableArray<ProjectInfo>> LoadProjectInfosFromPathAsync(string projectPath, DiagnosticReportingOptions
     reportingOptions, CancellationToken cancellationToken)
  at async Task<ImmutableArray<ProjectInfo>> LoadAsync(CancellationToken cancellationToken)
  at async Task<ImmutableArray<ProjectInfo>> LoadProjectInfoAsync(string projectFilePath, ProjectMap projectMap,
     IProgress<ProjectLoadProgress> progress, ILogger msbuildLogger, CancellationToken cancellationToken)
  at async Task<ImmutableArray<ProjectInfo>> LoadProjectInfoAsync(string projectFilePath, ProjectMap projectMap,
     IProgress<ProjectLoadProgress> progress, ILogger msbuildLogger, CancellationToken cancellationToken)
  at async Task<Project> OpenProjectAsync(string projectFilePath, ILogger msbuildLogger, IProgress<ProjectLoadProgress>
     progress, CancellationToken cancellationToken)
  at void MoveNext() in DotnetApiCatalog.Compile.cs:150
  at async (List<ValueTuple<IAssemblySymbol, Compilation>> symbol) Compile(ExtractMetadataConfig config, DotnetApiOptions
     options) in DotnetApiCatalog.Compile.cs:78
  at async Task <Exec>g__Build|5_0(ExtractMetadataConfig config, DotnetApiOptions options) in DotnetApiCatalog.cs:86
  at async Task Exec(MetadataJsonConfig config, DotnetApiOptions options, string configDirectory, string outputDirectory)
     in DotnetApiCatalog.cs:72
  at void <Execute>b__0() in DefaultCommand.cs:45
  at int Run(LogOptions options, Action run) in CommandHelper.cs:48
  at int Execute(CommandContext context, Options options) in DefaultCommand.cs:31
  at Task<int> Execute(CommandContext context, CommandSettings settings) in CommandOfT.cs:40
  at Task<int> Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration
     configuration) in CommandExecutor.cs:144
  at async Task<int> Execute(IConfiguration configuration, IEnumerable<string> args) in CommandExecutor.cs:83
  at async Task<int> RunAsync(IEnumerable<string> args) in CommandApp.cs:84
```

**Comment by filzrev** [comment]
Is it able to provide reproduceable files? 

I've tried to reproduce problems with Azure Pipelines with following settings.
But I can't be able to reproduce.

**azure-pipelines.yml**
``
trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:
- script: |
    dotnet tool install docfx -g
    pushd docs
    docfx metadata
    docfx build
    popd
  workingDirectory: "$(System.DefaultWorkingDirectory)"
```

**Comment by thejonan** [comment]
Here is the config file:

```yaml
{
  "metadata": [{
    "src": [{
      "files": ["Core/Core.csproj"],
      "src": "../"
    }, {
      "files": ["Nodes/Nodes.csproj", "Execution/Execution.csproj"],
      "src": "../"
    }],
    "dest": "api",
    "filter": "docfx-filter-config.yml",
    "disableGitFeatures": true,
    "disableDefaultFilter": false
  }],
  "build": {
    "content": [{
      "files": ["**.yml", "**.md"],
      "exclude": "docfx-filter-config.yml"
    }],
    "resource": [{
      "files": ["images/**"]
    }],
    "overwrite": [{
      "files": ["**.md"],
      "exclude": [
        "obj/**",
        "bin/**",
        "_site/**"
      ]
    }],
    "dest": "../public",
    "_globalMetadata": {
      "_appTitle": "MyTest™",
      "_enableSearch": true
    },
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": ["default"],
    "postProcessors": [],
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": true,
    "disableGitFeatures": true,
    "force": true
  }
}
```

With the filter file being:

```yaml
apiRules:
- include:
    uidRegex: ^Company\.Project\.Core.+
- exclude:
    uidRegex: _[^.]+$
```

I hope this would help.
