### ISSUE TITLE
[Feature Request] Generate docs ONLY for stuff with the /// comment.

### ISSUE THREAD

**Issue by GarfieldJiang** [dotnet/docfx#9979]
**Is your feature request related to a problem? Please describe.**
I want to hide some public APIs in the documentation. I want to include only those with the /// comments.

**Describe the solution you'd like**
Hope filter rules (apiRules in filterConfig.yml) have some option like
```
- apiRules:
- include:
    uidRegex: ^MyNamespace$
    type: Namespace
- exclude:
    withTripleSlashComment: false
```
Or options in docfx.json.

**Describe alternatives you've considered**
None.

**Additional context**
None.
