### ISSUE TITLE
[Feature Request] Create Categories or Tags for search

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#9993]
**Is your feature request related to a problem? Please describe.**
it might be interesting to be able to create categories for blogs and tags. This way, we could have a page that summarizes the categories or tags, allowing us to search either by tags or by categories.

And perhaps in the view of a post or article, below the titles, we could add categories and tags as visualizations.
```yaml
---
title: "Introduction -  IAC"
date: 2024-03-16
tags: 
  - Automation
  - PowerShell
  - IAC
  - Terraform
  - Packer
  - Vagrant
  - Vault
categories:
  - Iac
```
